/**
 * [AI-CONTEXT]
 * @file trivia_questions.h
 * @role Banque de questions « Trial Poursuite » — 720+ questions FR en flash.
 * @architecture_constraint Toutes les chaînes sont `static const` en PROGMEM/flash.
 *      Budget ~400 Ko max. Le gameplay (trivia_game.cpp) ne hardcode AUCUNE question.
 *      Répartition : ~40% Facile (0), ~40% Moyen (1), ~20% Difficile (2) par catégorie.
 * @ai_instruction Ne JAMAIS modifier les questions depuis le .cpp. Pour ajouter des
 *      questions, respecter le format TriviaQuestion et incrémenter le #define + static_assert.
 */
#pragma once
#include <cstdint>

// TRIVIA_NCAT peut être défini dans trivia_game.h ; garde-fou pour compilation autonome.
#ifndef TRIVIA_NCAT
#define TRIVIA_NCAT 6
#endif

// --- Compteurs par catégorie (preuve de volume) ---
#define TRIVIA_Q_GEO   120
#define TRIVIA_Q_ENT   120
#define TRIVIA_Q_HIST  120
#define TRIVIA_Q_ART   120
#define TRIVIA_Q_SCI   120
#define TRIVIA_Q_SPO   120
#define TRIVIA_Q_TOTAL (TRIVIA_Q_GEO + TRIVIA_Q_ENT + TRIVIA_Q_HIST + TRIVIA_Q_ART + TRIVIA_Q_SCI + TRIVIA_Q_SPO)
static_assert(TRIVIA_Q_TOTAL >= 720, "Banque insuffisante : minimum 720 questions requises");

// --- Format d'une question (struct C fixe, compacte) ---
struct TriviaQuestion {
    uint8_t     category;    // 0..5
    uint8_t     difficulty;  // 0=Facile, 1=Moyen, 2=Difficile
    const char* q;           // énoncé ≤ 140 chars
    const char* a;           // bonne réponse ≤ 48 chars
    const char* w1;          // leurre 1
    const char* w2;          // leurre 2
    const char* w3;          // leurre 3
};

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIE 0 : GÉOGRAPHIE (Bleu) — pays, capitales, reliefs, fleuves
// ═══════════════════════════════════════════════════════════════════════════════
static const TriviaQuestion QUESTIONS_GEO[TRIVIA_Q_GEO] = {
    // --- Facile (48 questions) ---
    {0,0,"Quelle est la capitale de la France ?","Paris","Lyon","Marseille","Bordeaux"},
    {0,0,"Quel est le plus long fleuve de France ?","La Loire","La Seine","Le Rhône","La Garonne"},
    {0,0,"Quel pays a pour capitale Tokyo ?","Le Japon","La Chine","La Corée du Sud","La Thaïlande"},
    {0,0,"Quel océan borde la côte ouest de la France ?","L'Atlantique","Le Pacifique","L'Indien","L'Arctique"},
    {0,0,"Quelle est la capitale de l'Espagne ?","Madrid","Barcelone","Séville","Valence"},
    {0,0,"Quel est le plus grand pays du monde en superficie ?","La Russie","Le Canada","Les États-Unis","La Chine"},
    {0,0,"Quel pays a la forme d'une botte ?","L'Italie","Le Portugal","La Grèce","La Croatie"},
    {0,0,"Quelle est la capitale de l'Allemagne ?","Berlin","Munich","Hambourg","Francfort"},
    {0,0,"Quel continent abrite le Sahara ?","L'Afrique","L'Asie","L'Océanie","L'Amérique du Sud"},
    {0,0,"Quel pays est surnommé « l'Hexagone » ?","La France","La Belgique","La Suisse","Le Portugal"},
    {0,0,"Quelle est la capitale du Royaume-Uni ?","Londres","Manchester","Édimbourg","Dublin"},
    {0,0,"Quel fleuve traverse Paris ?","La Seine","La Loire","Le Rhône","La Marne"},
    {0,0,"Quel est le plus haut sommet des Alpes ?","Le Mont Blanc","Le Cervin","Le Mont Rose","La Meije"},
    {0,0,"Quelle mer sépare la France de l'Angleterre ?","La Manche","La mer du Nord","La Méditerranée","L'Atlantique"},
    {0,0,"Quel pays a pour capitale Rome ?","L'Italie","L'Espagne","Le Portugal","La Grèce"},
    {0,0,"Quel est le plus grand océan du monde ?","Le Pacifique","L'Atlantique","L'Indien","L'Arctique"},
    {0,0,"Quelle est la capitale de la Belgique ?","Bruxelles","Anvers","Gand","Bruges"},
    {0,0,"Quel pays est le plus peuplé d'Europe ?","La Russie","L'Allemagne","La France","Le Royaume-Uni"},
    {0,0,"Quel désert se trouve en Mongolie ?","Le Gobi","Le Sahara","Le Kalahari","L'Atacama"},
    {0,0,"Quelle est la capitale de la Suisse ?","Berne","Zurich","Genève","Lausanne"},
    {0,0,"Quel fleuve traverse l'Égypte ?","Le Nil","Le Tigre","L'Euphrate","Le Congo"},
    {0,0,"Quel pays a pour capitale Lisbonne ?","Le Portugal","L'Espagne","Le Brésil","Le Maroc"},
    {0,0,"Quelle île française est surnommée « l'île de Beauté » ?","La Corse","La Réunion","La Martinique","Tahiti"},
    {0,0,"Quel est le plus petit pays du monde ?","Le Vatican","Monaco","Malte","Saint-Marin"},
    {0,0,"Quelle est la capitale des Pays-Bas ?","Amsterdam","La Haye","Rotterdam","Utrecht"},
    {0,0,"Quel pays est traversé par l'équateur en Afrique ?","Le Gabon","Le Sénégal","Le Maroc","L'Algérie"},
    {0,0,"Quel est le plus grand lac d'Afrique ?","Le lac Victoria","Le lac Tanganyika","Le lac Tchad","Le lac Malawi"},
    {0,0,"Quelle est la capitale de l'Australie ?","Canberra","Sydney","Melbourne","Brisbane"},
    {0,0,"Quel pays a pour capitale Ottawa ?","Le Canada","Les États-Unis","Le Mexique","Le Brésil"},
    {0,0,"Quel massif montagneux se trouve au sud de la France ?","Les Pyrénées","Les Vosges","Le Jura","Le Massif central"},
    {0,0,"Quelle est la capitale du Japon ?","Tokyo","Osaka","Kyoto","Nagoya"},
    {0,0,"Quel détroit sépare l'Europe de l'Afrique ?","Gibraltar","Le Bosphore","Le détroit de Béring","Le détroit d'Ormuz"},
    {0,0,"Quel pays a pour capitale Vienne ?","L'Autriche","La Hongrie","La Tchéquie","La Slovaquie"},
    {0,0,"Quelle est la plus grande île de Méditerranée ?","La Sicile","La Sardaigne","Chypre","La Crète"},
    {0,0,"Quel pays scandinave a pour capitale Stockholm ?","La Suède","La Norvège","Le Danemark","La Finlande"},
    {0,0,"Quel fleuve se jette dans la Méditerranée à Marseille ?","Aucun, c'est le Rhône à Arles","L'Hérault","Le Var","La Durance"},
    {0,0,"Quelle est la capitale du Maroc ?","Rabat","Casablanca","Marrakech","Fès"},
    {0,0,"Quel pays est entièrement entouré par l'Afrique du Sud ?","Le Lesotho","Le Swaziland","Le Botswana","Le Mozambique"},
    {0,0,"Quel est le plus long fleuve du monde ?","Le Nil","L'Amazone","Le Mississippi","Le Yangtsé"},
    {0,0,"Quelle est la capitale de la Grèce ?","Athènes","Thessalonique","Héraklion","Patras"},
    {0,0,"Quel océan entoure Madagascar ?","L'Indien","L'Atlantique","Le Pacifique","L'Arctique"},
    {0,0,"Quel pays a pour capitale Copenhague ?","Le Danemark","La Suède","La Norvège","L'Islande"},
    {0,0,"Quelle chaîne de montagnes sépare l'Europe de l'Asie ?","L'Oural","Le Caucase","Les Carpates","L'Himalaya"},
    {0,0,"Quel est le plus grand pays d'Afrique en superficie ?","L'Algérie","Le Soudan","Le Congo","Le Niger"},
    {0,0,"Quelle est la capitale de l'Argentine ?","Buenos Aires","Santiago","Montevideo","Lima"},
    {0,0,"Quel pays a pour capitale Ankara ?","La Turquie","La Syrie","L'Irak","L'Iran"},
    {0,0,"Quel volcan est le plus haut d'Europe ?","L'Etna","Le Vésuve","Le Stromboli","Le Puy de Dôme"},
    {0,0,"Quelle est la capitale de l'Inde ?","New Delhi","Bombay","Calcutta","Bangalore"},
    // --- Moyen (48 questions) ---
    {0,1,"Quelle est la capitale du Kazakhstan ?","Astana","Almaty","Tachkent","Bichkek"},
    {0,1,"Quel est le plus profond lac du monde ?","Le Baïkal","Le Tanganyika","Le Titicaca","Le Supérieur"},
    {0,1,"Quel pays possède le plus grand nombre de fuseaux horaires ?","La France","La Russie","Les États-Unis","Le Royaume-Uni"},
    {0,1,"Quelle est la capitale du Myanmar ?","Naypyidaw","Rangoun","Mandalay","Vientiane"},
    {0,1,"Quel fleuve traverse Budapest ?","Le Danube","Le Rhin","L'Elbe","La Vistule"},
    {0,1,"Quel est le point culminant de l'Afrique ?","Le Kilimandjaro","Le mont Kenya","Le Ras Dashan","Le Tubkal"},
    {0,1,"Quelle est la capitale du Nigeria ?","Abuja","Lagos","Kano","Ibadan"},
    {0,1,"Quel pays d'Amérique du Sud n'a pas de façade maritime ?","La Bolivie","Le Paraguay","Les deux","L'Uruguay"},
    {0,1,"Quel est le plus grand archipel du monde ?","L'Indonésie","Les Philippines","Le Japon","Les Maldives"},
    {0,1,"Quelle est la capitale de la Nouvelle-Zélande ?","Wellington","Auckland","Christchurch","Hamilton"},
    {0,1,"Quel détroit relie la mer Noire à la Méditerranée ?","Le Bosphore","Gibraltar","Le détroit d'Ormuz","Le canal de Suez"},
    {0,1,"Quel pays a pour capitale Addis-Abeba ?","L'Éthiopie","Le Kenya","La Somalie","L'Érythrée"},
    {0,1,"Quel est le plus haut sommet d'Amérique du Sud ?","L'Aconcagua","Le Chimborazo","Le Huascarán","Le Cotopaxi"},
    {0,1,"Quelle est la capitale de la Colombie ?","Bogotá","Medellín","Cali","Caracas"},
    {0,1,"Quel fleuve traverse la ville de Lyon ?","Le Rhône","La Saône","Les deux","La Loire"},
    {0,1,"Quel pays est enclavé entre la France et l'Espagne ?","Andorre","Le Luxembourg","Monaco","Le Liechtenstein"},
    {0,1,"Quelle est la capitale du Pérou ?","Lima","Cusco","Arequipa","Quito"},
    {0,1,"Quel est le plus grand désert chaud du monde ?","Le Sahara","L'Arabie","Le Kalahari","Le Thar"},
    {0,1,"Quelle mer est la plus salée du monde ?","La mer Morte","La mer Rouge","La mer Caspienne","La mer d'Aral"},
    {0,1,"Quel pays a pour capitale Tbilissi ?","La Géorgie","L'Arménie","L'Azerbaïdjan","Le Turkménistan"},
    {0,1,"Quel est le plus long fleuve d'Europe ?","La Volga","Le Danube","Le Rhin","L'Oural"},
    {0,1,"Quelle est la capitale du Sénégal ?","Dakar","Abidjan","Bamako","Conakry"},
    {0,1,"Quel pays possède la plus longue côte au monde ?","Le Canada","La Russie","L'Australie","La Norvège"},
    {0,1,"Quel est le plus haut sommet d'Europe de l'Ouest ?","Le Mont Blanc","Le Zugspitze","Le Mulhacén","Le Grand Combin"},
    {0,1,"Quelle est la capitale de la Croatie ?","Zagreb","Split","Dubrovnik","Rijeka"},
    {0,1,"Quel fleuve traverse la ville de Toulouse ?","La Garonne","Le Tarn","L'Ariège","Le Lot"},
    {0,1,"Quel pays a pour capitale Katmandou ?","Le Népal","Le Bhoutan","Le Tibet","Le Sri Lanka"},
    {0,1,"Quel est le plus grand pays d'Amérique du Sud ?","Le Brésil","L'Argentine","Le Pérou","La Colombie"},
    {0,1,"Quelle est la capitale de la Tanzanie ?","Dodoma","Dar es Salam","Nairobi","Kampala"},
    {0,1,"Quel canal relie l'Atlantique au Pacifique ?","Le canal de Panama","Le canal de Suez","Le canal de Corinthe","Le canal de Kiel"},
    {0,1,"Quel pays a pour capitale Reykjavik ?","L'Islande","La Norvège","Les îles Féroé","Le Groenland"},
    {0,1,"Quelle est la plus haute cascade d'Europe ?","Le Vinnufossen","Le Staubbach","La cascade de Gavarnie","Le Rhin"},
    {0,1,"Quel pays africain a pour capitale Luanda ?","L'Angola","Le Mozambique","La Zambie","Le Congo"},
    {0,1,"Quel est le plus grand pays d'Océanie ?","L'Australie","La Papouasie","La Nouvelle-Zélande","Fidji"},
    {0,1,"Quelle est la capitale de la Roumanie ?","Bucarest","Budapest","Sofia","Belgrade"},
    {0,1,"Quel fleuve sépare la France de l'Allemagne ?","Le Rhin","La Moselle","La Sarre","L'Ill"},
    {0,1,"Quel pays a pour capitale Hanoï ?","Le Viêt Nam","La Thaïlande","Le Cambodge","Le Laos"},
    {0,1,"Quel est le plus haut sommet du Japon ?","Le mont Fuji","Le mont Kita","Le mont Hotaka","Le mont Yari"},
    {0,1,"Quelle est la capitale de l'Ukraine ?","Kiev","Odessa","Kharkiv","Lviv"},
    {0,1,"Quel pays est le plus petit d'Amérique du Sud ?","Le Suriname","L'Uruguay","La Guyane","L'Équateur"},
    {0,1,"Quel est le plus grand lac d'Amérique du Nord ?","Le lac Supérieur","Le lac Michigan","Le lac Huron","Le lac Ontario"},
    {0,1,"Quelle est la capitale de l'Irlande ?","Dublin","Belfast","Cork","Galway"},
    {0,1,"Quel pays a pour capitale Quito ?","L'Équateur","Le Pérou","La Colombie","La Bolivie"},
    {0,1,"Quel est le plus haut plateau du monde ?","Le Tibet","L'Altiplano","Le Deccan","Le Colorado"},
    {0,1,"Quelle est la capitale de la Finlande ?","Helsinki","Tampere","Turku","Espoo"},
    {0,1,"Quel fleuve traverse la ville de Nantes ?","La Loire","La Vilaine","L'Erdre","La Sèvre"},
    {0,1,"Quel pays a pour capitale Damas ?","La Syrie","Le Liban","La Jordanie","L'Irak"},
    {0,1,"Quel est le plus grand golfe du monde ?","Le golfe du Mexique","Le golfe Persique","Le golfe de Gascogne","Le golfe du Bengale"},
    // --- Difficile (24 questions) ---
    {0,2,"Quelle est la capitale du Bhoutan ?","Thimphou","Paro","Punakha","Jakar"},
    {0,2,"Quel est le point le plus bas émergé de la Terre ?","La mer Morte","La dépression de Qattara","Le lac Assal","La vallée de la Mort"},
    {0,2,"Quelle est la capitale du Sri Lanka ?","Sri Jayawardenapura","Colombo","Kandy","Galle"},
    {0,2,"Quel pays possède l'île de Socotra ?","Le Yémen","Oman","La Somalie","L'Érythrée"},
    {0,2,"Quel est le plus haut sommet d'Océanie ?","Le Puncak Jaya","Le mont Cook","Le mont Wilhelm","Le Kosciuszko"},
    {0,2,"Quelle est la capitale du Belize ?","Belmopan","Belize City","San Ignacio","Orange Walk"},
    {0,2,"Quel fleuve traverse la capitale du Congo ?","Le Congo","L'Oubangui","La Sangha","Le Kouilou"},
    {0,2,"Quel est le plus petit pays d'Afrique ?","Les Seychelles","Sao Tomé","Le Cap-Vert","Les Comores"},
    {0,2,"Quelle est la capitale du Turkménistan ?","Achgabat","Tachkent","Douchanbé","Bichkek"},
    {0,2,"Quel pays a la plus faible altitude moyenne ?","Les Maldives","Le Qatar","Le Bangladesh","Les Pays-Bas"},
    {0,2,"Quel est le plus long tunnel ferroviaire du monde ?","Le Saint-Gothard","Le tunnel sous la Manche","Le Seikan","Le Lötschberg"},
    {0,2,"Quelle est la capitale du Lesotho ?","Maseru","Mbabane","Lobamba","Maputo"},
    {0,2,"Quel pays possède le plus de volcans actifs ?","L'Indonésie","Le Japon","L'Islande","Le Chili"},
    {0,2,"Quel est le plus grand bassin fluvial du monde ?","L'Amazone","Le Congo","Le Mississippi","Le Nil"},
    {0,2,"Quelle est la capitale de la Mauritanie ?","Nouakchott","Nouadhibou","Bamako","Dakar"},
    {0,2,"Quel détroit sépare l'Alaska de la Russie ?","Le détroit de Béring","Le détroit de Davis","Le détroit de Cook","Le détroit de Magellan"},
    {0,2,"Quel est le plus haut sommet des Andes équatoriennes ?","Le Chimborazo","Le Cotopaxi","Le Cayambe","L'Antisana"},
    {0,2,"Quelle est la capitale du Suriname ?","Paramaribo","Georgetown","Cayenne","Bridgetown"},
    {0,2,"Quel pays est le plus densément peuplé au monde ?","Monaco","Bangladesh","Singapour","Malte"},
    {0,2,"Quel est le plus ancien désert du monde ?","Le Namib","Le Sahara","L'Atacama","Le Kalahari"},
    {0,2,"Quelle est la capitale du Kirghizistan ?","Bichkek","Douchanbé","Achgabat","Astana"},
    {0,2,"Quel pays possède le plus grand nombre d'îles ?","La Suède","La Finlande","La Norvège","L'Indonésie"},
    {0,2,"Quel est le point culminant de la France métropolitaine ?","Le Mont Blanc","Le Dôme du Goûter","Les Écrins","Le Vignemale"},
    {0,2,"Quelle est la capitale du Botswana ?","Gaborone","Francistown","Windhoek","Lusaka"},
};

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIE 1 : DIVERTISSEMENT (Rose) — cinéma, musique, TV, jeux
// ═══════════════════════════════════════════════════════════════════════════════
static const TriviaQuestion QUESTIONS_ENT[TRIVIA_Q_ENT] = {
    // --- Facile (48 questions) ---
    {1,0,"Qui a réalisé le film « Titanic » (1997) ?","James Cameron","Steven Spielberg","Ridley Scott","Christopher Nolan"},
    {1,0,"Quel groupe a chanté « Bohemian Rhapsody » ?","Queen","The Beatles","Pink Floyd","Led Zeppelin"},
    {1,0,"Quel acteur incarne Jack Sparrow ?","Johnny Depp","Orlando Bloom","Brad Pitt","Tom Cruise"},
    {1,0,"Quel est le premier film de la saga Harry Potter ?","La Pierre philosophale","La Chambre des secrets","Le Prisonnier d'Azkaban","L'Ordre du Phénix"},
    {1,0,"Qui chante « Like a Rolling Stone » ?","Bob Dylan","Elvis Presley","The Rolling Stones","Bruce Springsteen"},
    {1,0,"Quel dessin animé Disney met en scène un lionceau ?","Le Roi Lion","Bambi","Le Livre de la jungle","Tarzan"},
    {1,0,"Quel acteur joue Iron Man dans le MCU ?","Robert Downey Jr.","Chris Evans","Chris Hemsworth","Mark Ruffalo"},
    {1,0,"Quelle série TV se déroule à Westeros ?","Game of Thrones","Vikings","The Witcher","Le Seigneur des Anneaux"},
    {1,0,"Qui a composé la musique de « Star Wars » ?","John Williams","Hans Zimmer","Ennio Morricone","Danny Elfman"},
    {1,0,"Quel film d'animation Pixar parle d'émotions ?","Vice-Versa","Toy Story","Là-Haut","Coco"},
    {1,0,"Quel chanteur est surnommé « The King of Pop » ?","Michael Jackson","Elvis Presley","Prince","Freddie Mercury"},
    {1,0,"Quel jeu vidéo met en scène un plombier italien ?","Super Mario Bros","Sonic","Zelda","Donkey Kong"},
    {1,0,"Qui réalise « Pulp Fiction » ?","Quentin Tarantino","Martin Scorsese","David Fincher","Guy Ritchie"},
    {1,0,"Quel film a pour héros un certain Forrest ?","Forrest Gump","Rain Man","Le Pianiste","Gladiator"},
    {1,0,"Quel groupe français a chanté « Get Lucky » ?","Daft Punk","Justice","Air","Phoenix"},
    {1,0,"Quel acteur incarne Batman dans « The Dark Knight » ?","Christian Bale","Ben Affleck","Michael Keaton","George Clooney"},
    {1,0,"Quelle série met en scène un prof de chimie devenu dealer ?","Breaking Bad","Narcos","Ozark","Peaky Blinders"},
    {1,0,"Quel film Disney se passe dans le royaume d'Arendelle ?","La Reine des Neiges","Raiponce","Rebelle","Mulan"},
    {1,0,"Qui chante « Billie Jean » ?","Michael Jackson","Prince","Stevie Wonder","Marvin Gaye"},
    {1,0,"Quel est le nom du vaisseau dans « Alien » ?","Le Nostromo","L'Enterprise","Le Falcon","Le Discovery"},
    {1,0,"Quel acteur joue le rôle de James Bond dans « Casino Royale » ?","Daniel Craig","Pierce Brosnan","Sean Connery","Roger Moore"},
    {1,0,"Quel film Pixar met en scène un poisson-clown ?","Le Monde de Nemo","Le Monde de Dory","Shark Tale","Némo"},
    {1,0,"Qui a chanté « Imagine » ?","John Lennon","Paul McCartney","Bob Dylan","Elton John"},
    {1,0,"Quel jeu de société implique d'acheter des rues ?","Le Monopoly","Le Risk","Le Cluedo","Le Scrabble"},
    {1,0,"Quel film met en scène un anneau à détruire ?","Le Seigneur des Anneaux","Harry Potter","Narnia","Eragon"},
    {1,0,"Quel chanteur français est surnommé « l'Idole des jeunes » ?","Johnny Hallyday","Charles Aznavour","Jacques Brel","Serge Gainsbourg"},
    {1,0,"Quel studio a créé Mickey Mouse ?","Disney","Warner Bros","Pixar","DreamWorks"},
    {1,0,"Quel film de 1994 montre un prisonnier qui s'évade ?","Les Évadés","Le Trou","Papillon","Midnight Express"},
    {1,0,"Qui interprète le Joker dans « The Dark Knight » ?","Heath Ledger","Jack Nicholson","Jared Leto","Joaquin Phoenix"},
    {1,0,"Quel groupe a chanté « Smells Like Teen Spirit » ?","Nirvana","Pearl Jam","Soundgarden","Alice in Chains"},
    {1,0,"Quel film d'animation japonais parle d'un voyage dans un bain ?","Le Voyage de Chihiro","Mon voisin Totoro","Princesse Mononoké","Akira"},
    {1,0,"Quel acteur incarne Wolverine ?","Hugh Jackman","Ryan Reynolds","Chris Evans","Tom Hardy"},
    {1,0,"Quel film met en scène un requin géant (1975) ?","Les Dents de la mer","Piranha","En eaux troubles","Peur bleue"},
    {1,0,"Qui a réalisé « E.T. l'extra-terrestre » ?","Steven Spielberg","George Lucas","James Cameron","Ridley Scott"},
    {1,0,"Quel jeu vidéo se déroule dans le royaume d'Hyrule ?","Zelda","Final Fantasy","Dragon Quest","Dark Souls"},
    {1,0,"Quel film met en scène un robot qui tombe amoureux ?","WALL-E","Terminator","I, Robot","Ex Machina"},
    {1,0,"Qui chante « Purple Rain » ?","Prince","Jimi Hendrix","Lenny Kravitz","Stevie Wonder"},
    {1,0,"Quel film français a remporté l'Oscar du meilleur film en 2012 ?","The Artist","Intouchables","Amélie Poulain","La Môme"},
    {1,0,"Quel personnage de Marvel utilise un bouclier ?","Captain America","Thor","Hulk","Spider-Man"},
    {1,0,"Quel film met en scène un parc de dinosaures ?","Jurassic Park","King Kong","Godzilla","Congo"},
    {1,0,"Qui a composé « La Lettre à Élise » ?","Beethoven","Mozart","Chopin","Bach"},
    {1,0,"Quel film d'animation montre un rat qui cuisine ?","Ratatouille","Le Chef","Les Indestructibles","Cars"},
    {1,0,"Quel acteur joue Neo dans « Matrix » ?","Keanu Reeves","Laurence Fishburne","Hugo Weaving","Will Smith"},
    {1,0,"Quel groupe a chanté « Hotel California » ?","Eagles","Fleetwood Mac","The Doors","Creedence"},
    {1,0,"Quel film met en scène un clown tueur dans un égout ?","Ça","Halloween","Freddy","Scream"},
    {1,0,"Quel jeu vidéo est un battle royale avec 100 joueurs ?","Fortnite","Minecraft","Tetris","Pac-Man"},
    {1,0,"Qui a réalisé « Inception » ?","Christopher Nolan","David Fincher","Ridley Scott","Denis Villeneuve"},
    {1,0,"Quel film met en scène un taxi volant à New York ?","Le Cinquième Élément","Blade Runner","Retour vers le futur","Star Wars"},
    // --- Moyen (48 questions) ---
    {1,1,"Quel acteur incarne le Comte de Monte-Cristo (2024) ?","Pierre Niney","Jean Dujardin","Gaspard Ulliel","Romain Duris"},
    {1,1,"Quel groupe a sorti l'album « Abbey Road » ?","The Beatles","The Rolling Stones","The Who","The Kinks"},
    {1,1,"Quel réalisateur a fait « 2001, l'Odyssée de l'espace » ?","Stanley Kubrick","Ridley Scott","Steven Spielberg","George Lucas"},
    {1,1,"Quelle actrice joue Katniss dans « Hunger Games » ?","Jennifer Lawrence","Emma Stone","Shailene Woodley","Kristen Stewart"},
    {1,1,"Quel film de Miyazaki met en scène un cochon pilote ?","Porco Rosso","Le Vent se lève","Kiki la petite sorcière","Ponyo"},
    {1,1,"Qui a composé la bande originale d'« Interstellar » ?","Hans Zimmer","John Williams","Ludwig Göransson","Trent Reznor"},
    {1,1,"Quel film a remporté la Palme d'or à Cannes en 2019 ?","Parasite","La Vie d'Adèle","Dheepan","The Square"},
    {1,1,"Quel chanteur a sorti l'album « Thriller » ?","Michael Jackson","Prince","Stevie Wonder","Lionel Richie"},
    {1,1,"Quel acteur joue le rôle-titre dans « Gladiator » ?","Russell Crowe","Gerard Butler","Joaquin Phoenix","Orlando Bloom"},
    {1,1,"Quel film de Nolan se déroule dans un rêve partagé ?","Inception","Tenet","Interstellar","Memento"},
    {1,1,"Quelle série TV suit un chimiste et un avocat ?","Better Call Saul","Breaking Bad","The Wire","Fargo"},
    {1,1,"Quel groupe a chanté « Stairway to Heaven » ?","Led Zeppelin","Deep Purple","Black Sabbath","Pink Floyd"},
    {1,1,"Quel film met en scène un androïde chasseur de primes ?","Blade Runner","Terminator","Alien","Westworld"},
    {1,1,"Qui a réalisé « Le Fabuleux Destin d'Amélie Poulain » ?","Jean-Pierre Jeunet","Luc Besson","Michel Gondry","Cédric Klapisch"},
    {1,1,"Quel acteur incarne Gandalf dans « Le Seigneur des Anneaux » ?","Ian McKellen","Patrick Stewart","Ian Holm","Christopher Lee"},
    {1,1,"Quel film de 1999 montre un monde simulé ?","Matrix","Tron","Dark City","eXistenZ"},
    {1,1,"Quel groupe suédois a chanté « Dancing Queen » ?","ABBA","Roxette","Ace of Base","Europe"},
    {1,1,"Quel film met en scène un tueur en série et 7 péchés ?","Se7en","Le Silence des agneaux","Zodiac","Psychose"},
    {1,1,"Qui a réalisé « Le Parrain » ?","Francis Ford Coppola","Martin Scorsese","Sergio Leone","Brian De Palma"},
    {1,1,"Quel jeu vidéo de FromSoftware se déroule à Yharnam ?","Bloodborne","Dark Souls","Elden Ring","Sekiro"},
    {1,1,"Quel film d'animation montre des jouets qui prennent vie ?","Toy Story","Les Indestructibles","Monstres et Cie","Shrek"},
    {1,1,"Quel acteur joue le rôle de Vito Corleone jeune ?","Robert De Niro","Al Pacino","Marlon Brando","Joe Pesci"},
    {1,1,"Quel film de Denis Villeneuve se passe sur Arrakis ?","Dune","Premier Contact","Blade Runner 2049","Sicario"},
    {1,1,"Quel groupe a sorti « The Wall » ?","Pink Floyd","Genesis","Yes","King Crimson"},
    {1,1,"Quel film met en scène un naufragé et un tigre ?","L'Odyssée de Pi","Seul au monde","Cast Away","En pleine tempête"},
    {1,1,"Qui a réalisé « Parasite » ?","Bong Joon-ho","Park Chan-wook","Kim Ki-duk","Lee Chang-dong"},
    {1,1,"Quel acteur incarne le Dr House ?","Hugh Laurie","Bryan Cranston","Jon Hamm","Peter Dinklage"},
    {1,1,"Quel film de Tarantino se passe pendant la Seconde Guerre ?","Inglourious Basterds","Django Unchained","Kill Bill","Pulp Fiction"},
    {1,1,"Quel jeu vidéo open-world se déroule à Los Santos ?","GTA V","Red Dead Redemption","Watch Dogs","Saints Row"},
    {1,1,"Quel film met en scène un enfant et un alien (1982) ?","E.T.","Rencontres du 3e type","Super 8","Cocoon"},
    {1,1,"Quel chanteur a composé « Bohemian Rhapsody » ?","Freddie Mercury","Brian May","Roger Taylor","John Deacon"},
    {1,1,"Quel film de Scorsese dure plus de 3 heures (2019) ?","The Irishman","Les Affranchis","Le Loup de Wall Street","Casino"},
    {1,1,"Quel acteur joue le rôle de Tyler Durden ?","Brad Pitt","Edward Norton","Jared Leto","Ben Affleck"},
    {1,1,"Quel film met en scène un labyrinthe et un Minotaure ?","Le Labyrinthe de Pan","Percy Jackson","Le Choc des Titans","Narnia"},
    {1,1,"Quel groupe a chanté « Wish You Were Here » ?","Pink Floyd","Radiohead","The Cure","U2"},
    {1,1,"Quel film de 2010 montre un monde de rêves emboîtés ?","Inception","Source Code","Looper","Edge of Tomorrow"},
    {1,1,"Qui a réalisé « Le Silence des agneaux » ?","Jonathan Demme","David Fincher","Ridley Scott","Anthony Hopkins"},
    {1,1,"Quel acteur incarne le Capitaine Crochet (2024) ?","Jude Law","Johnny Depp","Jason Isaacs","Dustin Hoffman"},
    {1,1,"Quel film met en scène un homme qui rétrécit ?","L'Homme qui rétrécit","Chérie, j'ai rétréci les gosses","Ant-Man","Honey I Shrunk"},
    {1,1,"Quel jeu vidéo de 2022 se déroule dans « l'Entre-Terre » ?","Elden Ring","Dark Souls III","Sekiro","Bloodborne"},
    {1,1,"Quel film de Wes Anderson se passe dans un hôtel ?","The Grand Budapest Hotel","Moonrise Kingdom","La Famille Tenenbaum","L'Île aux chiens"},
    {1,1,"Quel acteur joue le rôle de Tony Montana ?","Al Pacino","Robert De Niro","Joe Pesci","Ray Liotta"},
    {1,1,"Quel film met en scène un pianiste pendant la Shoah ?","Le Pianiste","La Liste de Schindler","La Vie est belle","Le Fils de Saul"},
    {1,1,"Quel groupe a chanté « Creep » ?","Radiohead","Muse","Coldplay","Placebo"},
    {1,1,"Quel film de 1985 montre une DeLorean qui voyage dans le temps ?","Retour vers le futur","Terminator","Bill & Ted","Nimitz"},
    {1,1,"Qui a réalisé « Fight Club » ?","David Fincher","Quentin Tarantino","Guy Ritchie","Danny Boyle"},
    {1,1,"Quel acteur incarne le rôle-titre dans « Joker » (2019) ?","Joaquin Phoenix","Heath Ledger","Jared Leto","Jack Nicholson"},
    {1,1,"Quel film d'animation japonais montre une guerre entre clans ?","Princesse Mononoké","Nausicaä","Le Château dans le ciel","Le Vent se lève"},
    // --- Difficile (24 questions) ---
    {1,2,"Quel film a remporté le premier Oscar du meilleur film ?","Wings","Sunrise","Le Chanteur de jazz","Metropolis"},
    {1,2,"Quel acteur a refusé le rôle de Neo dans Matrix ?","Will Smith","Nicolas Cage","Leonardo DiCaprio","Tom Cruise"},
    {1,2,"Quel groupe a sorti l'album « Kid A » en 2000 ?","Radiohead","Muse","Coldplay","Arcade Fire"},
    {1,2,"Quel réalisateur a fait « Eraserhead » ?","David Lynch","David Cronenberg","Terry Gilliam","Alejandro Jodorowsky"},
    {1,2,"Quel film de Kurosawa a inspiré « Les 7 Mercenaires » ?","Les 7 Samouraïs","Rashomon","Yojimbo","Ran"},
    {1,2,"Quel acteur joue dans « There Will Be Blood » (2007) ?","Daniel Day-Lewis","Joaquin Phoenix","Paul Dano","Robert De Niro"},
    {1,2,"Quel film de Tarkovski se déroule dans une zone mystérieuse ?","Stalker","Solaris","Andreï Roublev","Le Miroir"},
    {1,2,"Quel groupe a composé « A Day in the Life » ?","The Beatles","The Rolling Stones","The Who","Pink Floyd"},
    {1,2,"Quel film de 1927 est un chef-d'œuvre de la SF muette ?","Metropolis","Le Cabinet du Dr Caligari","Nosferatu","L'Aurore"},
    {1,2,"Quel réalisateur a fait « Le Septième Sceau » ?","Ingmar Bergman","Federico Fellini","Akira Kurosawa","Luis Buñuel"},
    {1,2,"Quel acteur incarne le rôle-titre dans « Amadeus » ?","F. Murray Abraham","Tom Hulce","Ian McKellen","Gary Oldman"},
    {1,2,"Quel film de Godard est considéré comme fondateur de la Nouvelle Vague ?","À bout de souffle","Pierrot le Fou","Le Mépris","Une femme est une femme"},
    {1,2,"Quel jeu vidéo de 1998 a popularisé le FPS narratif ?","Half-Life","Quake","Doom","Unreal"},
    {1,2,"Quel compositeur a écrit la musique de « Lawrence d'Arabie » ?","Maurice Jarre","Ennio Morricone","Bernard Herrmann","Alex North"},
    {1,2,"Quel film de Bergman met en scène la Mort en personne ?","Le Septième Sceau","Cris et Chuchotements","Persona","Fanny et Alexandre"},
    {1,2,"Quel acteur a joué dans « Le Salaire de la peur » (1953) ?","Yves Montand","Jean Gabin","Charles Vanel","Les deux A et C"},
    {1,2,"Quel film de 1968 montre un monolithe noir ?","2001, l'Odyssée de l'espace","Planète interdite","Solaris","Contact"},
    {1,2,"Quel groupe a sorti « OK Computer » en 1997 ?","Radiohead","Oasis","Blur","The Verve"},
    {1,2,"Quel réalisateur a fait « Andreï Roublev » ?","Andreï Tarkovski","Sergueï Eisenstein","Nikita Mikhalkov","Elem Klimov"},
    {1,2,"Quel film de Hitchcock se déroule entièrement dans un appartement ?","Fenêtre sur cour","Psychose","Sueurs froides","La Corde"},
    {1,2,"Quel acteur incarne le rôle-titre dans « Raging Bull » ?","Robert De Niro","Al Pacino","Joe Pesci","Sylvester Stallone"},
    {1,2,"Quel film de 1975 de Spielberg a créé le blockbuster estival ?","Les Dents de la mer","Rencontres du 3e type","E.T.","Jurassic Park"},
    {1,2,"Quel jeu vidéo de 1986 a défini le metroidvania ?","Metroid","Castlevania","Zelda","Mega Man"},
    {1,2,"Quel compositeur a écrit « Le Sacre du printemps » ?","Stravinsky","Debussy","Ravel","Bartók"},
};

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIE 2 : HISTOIRE (Jaune) — dates, personnages, événements
// ═══════════════════════════════════════════════════════════════════════════════
static const TriviaQuestion QUESTIONS_HIST[TRIVIA_Q_HIST] = {
    // --- Facile (48 questions) ---
    {2,0,"En quelle année a eu lieu la Révolution française ?","1789","1776","1804","1815"},
    {2,0,"Qui était le premier empereur des Français ?","Napoléon Ier","Louis XVI","Charlemagne","Louis XIV"},
    {2,0,"En quelle année a commencé la Seconde Guerre mondiale ?","1939","1914","1941","1936"},
    {2,0,"Qui a découvert l'Amérique en 1492 ?","Christophe Colomb","Magellan","Vasco de Gama","Amerigo Vespucci"},
    {2,0,"Quel mur est tombé en 1989 ?","Le mur de Berlin","Le mur d'Hadrien","La Grande Muraille","Le mur des Lamentations"},
    {2,0,"Qui était le roi de France surnommé « le Roi-Soleil » ?","Louis XIV","Louis XVI","François Ier","Henri IV"},
    {2,0,"En quelle année l'homme a-t-il marché sur la Lune ?","1969","1961","1972","1957"},
    {2,0,"Qui a été le premier président des États-Unis ?","George Washington","Thomas Jefferson","Abraham Lincoln","John Adams"},
    {2,0,"Quelle civilisation a construit les pyramides de Gizeh ?","Les Égyptiens","Les Mayas","Les Grecs","Les Romains"},
    {2,0,"En quelle année a eu lieu le débarquement en Normandie ?","1944","1943","1945","1942"},
    {2,0,"Qui a écrit la Déclaration d'indépendance des USA ?","Thomas Jefferson","George Washington","Benjamin Franklin","John Adams"},
    {2,0,"Quel empire était dirigé par Jules César ?","L'Empire romain","L'Empire grec","L'Empire perse","L'Empire ottoman"},
    {2,0,"En quelle année a commencé la Première Guerre mondiale ?","1914","1918","1912","1916"},
    {2,0,"Qui a libéré la France avec le général de Gaulle ?","Les Alliés","Les Russes","Les Espagnols","Les Suisses"},
    {2,0,"Quel pharaon est célèbre pour son masque en or ?","Toutânkhamon","Ramsès II","Khéops","Akhenaton"},
    {2,0,"En quelle année la Bastille a-t-elle été prise ?","1789","1792","1799","1804"},
    {2,0,"Qui était surnommé « le Petit Caporal » ?","Napoléon","Louis XIV","Charlemagne","Henri IV"},
    {2,0,"Quel pays a lancé la première bombe atomique ?","Les États-Unis","L'URSS","L'Allemagne","Le Japon"},
    {2,0,"En quelle année a eu lieu la chute de l'Empire romain d'Occident ?","476","410","527","395"},
    {2,0,"Qui a été le premier homme dans l'espace ?","Youri Gagarine","Neil Armstrong","John Glenn","Alan Shepard"},
    {2,0,"Quel traité a mis fin à la Première Guerre mondiale ?","Le traité de Versailles","Le traité de Paris","Le traité de Vienne","Le traité de Rome"},
    {2,0,"Qui était le chancelier allemand pendant la Seconde Guerre ?","Hitler","Bismarck","Hindenburg","Goebbels"},
    {2,0,"En quelle année a eu lieu la Révolution russe ?","1917","1905","1922","1914"},
    {2,0,"Quel navigateur a fait le premier tour du monde ?","Magellan","Colomb","Vasco de Gama","Drake"},
    {2,0,"Qui a peint la chapelle Sixtine ?","Michel-Ange","Léonard de Vinci","Raphaël","Botticelli"},
    {2,0,"En quelle année a eu lieu le couronnement de Napoléon ?","1804","1799","1812","1815"},
    {2,0,"Quel peuple a inventé l'écriture cunéiforme ?","Les Sumériens","Les Égyptiens","Les Chinois","Les Grecs"},
    {2,0,"Qui était Cléopâtre ?","Reine d'Égypte","Impératrice romaine","Déesse grecque","Pharaonne de Nubie"},
    {2,0,"En quelle année a eu lieu la prise de Constantinople ?","1453","1492","1389","1517"},
    {2,0,"Quel roi a construit le château de Versailles ?","Louis XIV","Louis XIII","François Ier","Henri IV"},
    {2,0,"Qui a inventé l'imprimerie en Europe ?","Gutenberg","Léonard de Vinci","Galilée","Copernic"},
    {2,0,"En quelle année a eu lieu la bataille de Waterloo ?","1815","1812","1804","1799"},
    {2,0,"Quel pays a été le premier à abolir l'esclavage ?","Haïti","La France","Le Royaume-Uni","Les États-Unis"},
    {2,0,"Qui était le leader de l'Inde indépendante ?","Gandhi","Nehru","Bose","Patel"},
    {2,0,"En quelle année a eu lieu la Révolution d'Octobre ?","1917","1905","1921","1918"},
    {2,0,"Quel empire a été fondé par Gengis Khan ?","L'Empire mongol","L'Empire ottoman","L'Empire perse","L'Empire chinois"},
    {2,0,"Qui a été le dernier tsar de Russie ?","Nicolas II","Alexandre III","Pierre le Grand","Ivan le Terrible"},
    {2,0,"En quelle année a eu lieu la bataille de Verdun ?","1916","1914","1918","1915"},
    {2,0,"Quel pays a colonisé l'Indochine ?","La France","Le Royaume-Uni","Les Pays-Bas","Le Portugal"},
    {2,0,"Qui a été couronné empereur en 800 ?","Charlemagne","Clovis","Pépin le Bref","Louis le Pieux"},
    {2,0,"En quelle année a eu lieu la Révolution américaine ?","1776","1789","1812","1763"},
    {2,0,"Quel peuple a construit le Machu Picchu ?","Les Incas","Les Mayas","Les Aztèques","Les Olmèques"},
    {2,0,"Qui était le président français en 1940 ?","Albert Lebrun","De Gaulle","Pétain","Doumergue"},
    {2,0,"En quelle année a eu lieu la bataille d'Hastings ?","1066","1215","1453","1099"},
    {2,0,"Quel pays a été divisé en deux de 1949 à 1990 ?","L'Allemagne","La Corée","Le Viêt Nam","La Chine"},
    {2,0,"Qui a mené la marche du sel en Inde ?","Gandhi","Nehru","Bose","Ambedkar"},
    {2,0,"En quelle année a eu lieu la crise des missiles de Cuba ?","1962","1961","1963","1959"},
    {2,0,"Quel roi anglais a eu six femmes ?","Henri VIII","Henri VII","Édouard VI","Jacques Ier"},
    // --- Moyen (48 questions) ---
    {2,1,"En quelle année a eu lieu la bataille de Marignan ?","1515","1492","1525","1547"},
    {2,1,"Qui a été le premier empereur du Brésil ?","Pedro Ier","Pedro II","Dom João VI","Tiradentes"},
    {2,1,"En quelle année a eu lieu la Révolution de Juillet ?","1830","1848","1871","1789"},
    {2,1,"Quel traité a partagé le monde entre Espagne et Portugal ?","Le traité de Tordesillas","Le traité de Saragosse","Le traité de Paris","Le traité de Utrecht"},
    {2,1,"Qui était le dirigeant de l'URSS pendant la crise de Cuba ?","Khrouchtchev","Staline","Brezhnev","Gorbatchev"},
    {2,1,"En quelle année a eu lieu la Commune de Paris ?","1871","1848","1830","1793"},
    {2,1,"Quel pharaon a construit la grande pyramide de Gizeh ?","Khéops","Khéphren","Mykérinos","Djéser"},
    {2,1,"Qui a été le premier roi de France ?","Clovis","Charlemagne","Hugues Capet","Pépin le Bref"},
    {2,1,"En quelle année a eu lieu la bataille de Poitiers ?","732","711","751","800"},
    {2,1,"Quel navigateur a atteint le cap de Bonne-Espérance ?","Bartolomeu Dias","Vasco de Gama","Magellan","Colomb"},
    {2,1,"Qui a été le dernier empereur de Chine ?","Puyi","Sun Yat-sen","Mao Zedong","Kangxi"},
    {2,1,"En quelle année a eu lieu la Révolution culturelle chinoise ?","1966","1949","1958","1976"},
    {2,1,"Quel roi a signé la Magna Carta ?","Jean sans Terre","Richard Cœur de Lion","Henri II","Édouard Ier"},
    {2,1,"Qui a mené la révolte des esclaves à Saint-Domingue ?","Toussaint Louverture","Dessalines","Christophe","Pétion"},
    {2,1,"En quelle année a eu lieu la bataille d'Austerlitz ?","1805","1804","1812","1815"},
    {2,1,"Quel empire a été détruit par les Mongols en 1258 ?","Le califat abbasside","L'Empire byzantin","L'Empire perse","L'Empire ottoman"},
    {2,1,"Qui a été le premier président de la Ve République ?","De Gaulle","Pompidou","Mitterrand","Coty"},
    {2,1,"En quelle année a eu lieu la Révolution de Février en Russie ?","1917","1905","1918","1921"},
    {2,1,"Quel pays a été le premier à accorder le vote aux femmes ?","La Nouvelle-Zélande","La Finlande","L'Australie","La Norvège"},
    {2,1,"Qui était le chef des Gaulois à Alésia ?","Vercingétorix","Brennus","Ambiorix","Dumnorix"},
    {2,1,"En quelle année a eu lieu la Révolution iranienne ?","1979","1971","1981","1963"},
    {2,1,"Quel traité a mis fin à la guerre de Cent Ans ?","Aucun traité formel","Le traité de Troyes","Le traité de Brétigny","Le traité de Picquigny"},
    {2,1,"Qui a été le premier pape ?","Saint Pierre","Saint Paul","Saint Lin","Saint Clément"},
    {2,1,"En quelle année a eu lieu la bataille de Stalingrad ?","1942-1943","1941-1942","1943-1944","1944-1945"},
    {2,1,"Quel pays a inventé la poudre à canon ?","La Chine","L'Inde","Le monde arabe","L'Europe"},
    {2,1,"Qui a été le dernier président de l'URSS ?","Gorbatchev","Eltsine","Brezhnev","Andropov"},
    {2,1,"En quelle année a eu lieu la Révolution de Velours ?","1989","1991","1987","1993"},
    {2,1,"Quel roi a été guillotiné en 1793 ?","Louis XVI","Louis XV","Charles X","Louis XVIII"},
    {2,1,"Qui a mené l'expédition des Mille ?","Garibaldi","Mazzini","Cavour","Victor-Emmanuel II"},
    {2,1,"En quelle année a eu lieu la bataille de Trafalgar ?","1805","1804","1812","1798"},
    {2,1,"Quel empire a été fondé par Cyrus le Grand ?","L'Empire perse","L'Empire babylonien","L'Empire assyrien","L'Empire mède"},
    {2,1,"Qui a été le premier secrétaire général de l'ONU ?","Trygve Lie","Dag Hammarskjöld","U Thant","Kurt Waldheim"},
    {2,1,"En quelle année a eu lieu la Révolution mexicaine ?","1910","1917","1920","1898"},
    {2,1,"Quel pays a été le premier à se décoloniser en Afrique ?","Le Ghana","Le Sénégal","La Guinée","Le Nigeria"},
    {2,1,"Qui était le chancelier de fer allemand ?","Bismarck","Guillaume Ier","Hindenburg","Metternich"},
    {2,1,"En quelle année a eu lieu la bataille de Hastings ?","1066","1099","1215","1453"},
    {2,1,"Quel traité a créé la CEE en 1957 ?","Le traité de Rome","Le traité de Maastricht","Le traité de Paris","Le traité de Lisbonne"},
    {2,1,"Qui a été le premier pharaon d'Égypte unifiée ?","Narmer","Khéops","Ménès","Les deux A et C"},
    {2,1,"En quelle année a eu lieu la Révolution haïtienne ?","1791","1804","1789","1815"},
    {2,1,"Quel pays a été le premier à utiliser l'arme nucléaire ?","Les États-Unis","L'URSS","Le Royaume-Uni","L'Allemagne"},
    {2,1,"Qui a été le dernier roi de France ?","Louis-Philippe Ier","Charles X","Louis XVIII","Napoléon III"},
    {2,1,"En quelle année a eu lieu la bataille de Gettysburg ?","1863","1861","1865","1862"},
    {2,1,"Quel empire a été dirigé par Soliman le Magnifique ?","L'Empire ottoman","L'Empire perse","L'Empire moghol","L'Empire byzantin"},
    {2,1,"Qui a été le premier président noir des États-Unis ?","Barack Obama","Martin Luther King","Jesse Jackson","Colin Powell"},
    {2,1,"En quelle année a eu lieu la Révolution des Œillets ?","1974","1968","1975","1981"},
    {2,1,"Quel pays a été le premier à reconnaître les États-Unis ?","Le Maroc","La France","L'Espagne","Les Pays-Bas"},
    {2,1,"Qui a été le dernier empereur byzantin ?","Constantin XI","Justinien","Basile II","Alexis Ier"},
    {2,1,"En quelle année a eu lieu la Révolution de 1848 en France ?","1848","1830","1851","1871"},
    // --- Difficile (24 questions) ---
    {2,2,"En quelle année a eu lieu la bataille de Lépante ?","1571","1453","1529","1600"},
    {2,2,"Qui a été le dernier empereur du Saint-Empire ?","François II","Charles Quint","Ferdinand Ier","Maximilien Ier"},
    {2,2,"En quelle année a eu lieu la Révolution de Zanzibar ?","1964","1961","1963","1967"},
    {2,2,"Quel traité a mis fin à la guerre de Trente Ans ?","Les traités de Westphalie","Le traité d'Utrecht","Le traité de Ryswick","Le traité de Nimègue"},
    {2,2,"Qui a été le premier roi d'Italie unifiée ?","Victor-Emmanuel II","Garibaldi","Cavour","Umberto Ier"},
    {2,2,"En quelle année a eu lieu la bataille de Tours (Poitiers) ?","732","711","751","768"},
    {2,2,"Quel pays a été le premier à abolir la peine de mort ?","Le grand-duché de Toscane","La France","Le Venezuela","Le Portugal"},
    {2,2,"Qui a été le dernier roi d'Égypte ?","Farouk Ier","Fouad II","Nasser","Sadate"},
    {2,2,"En quelle année a eu lieu la Révolution des Jeunes-Turcs ?","1908","1913","1923","1897"},
    {2,2,"Quel traité a partagé l'Afrique entre Européens ?","La conférence de Berlin","Le traité de Tordesillas","Le traité de Versailles","Le traité de Paris"},
    {2,2,"Qui a été le premier président du Sénégal indépendant ?","Léopold Sédar Senghor","Abdou Diouf","Mamadou Dia","Lamine Guèye"},
    {2,2,"En quelle année a eu lieu la bataille de Crécy ?","1346","1356","1415","1337"},
    {2,2,"Quel empire a été fondé par Tamerlan ?","L'Empire timouride","L'Empire moghol","L'Empire ottoman","L'Empire perse"},
    {2,2,"Qui a été le dernier doge de Venise ?","Ludovico Manin","Marco Polo","Enrico Dandolo","Francesco Foscari"},
    {2,2,"En quelle année a eu lieu la Révolution de 1905 en Russie ?","1905","1917","1903","1907"},
    {2,2,"Quel traité a mis fin à la guerre de Sept Ans ?","Le traité de Paris (1763)","Le traité d'Utrecht","Le traité de Hubertsbourg","Les deux A et C"},
    {2,2,"Qui a été le premier empereur du Japon ?","Jimmu","Meiji","Hirohito","Akihito"},
    {2,2,"En quelle année a eu lieu la bataille de Kosovo Polje ?","1389","1453","1444","1526"},
    {2,2,"Quel pays a été le premier à se convertir au christianisme ?","L'Arménie","L'Empire romain","L'Éthiopie","La Géorgie"},
    {2,2,"Qui a été le dernier roi de Grèce ?","Constantin II","Georges II","Paul Ier","Alexandre Ier"},
    {2,2,"En quelle année a eu lieu la Révolution constitutionnelle persane ?","1906","1921","1908","1896"},
    {2,2,"Quel traité a créé la Société des Nations ?","Le traité de Versailles","Le traité de Genève","Le traité de Paris","Le pacte Briand-Kellogg"},
    {2,2,"Qui a été le premier président de la République turque ?","Mustafa Kemal Atatürk","İsmet İnönü","Enver Pacha","Celal Bayar"},
    {2,2,"En quelle année a eu lieu la Révolution de 1830 en Belgique ?","1830","1848","1831","1839"},
};

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIE 3 : ARTS & LITTÉRATURE (Marron) — livres, peinture, philo
// ═══════════════════════════════════════════════════════════════════════════════
static const TriviaQuestion QUESTIONS_ART[TRIVIA_Q_ART] = {
    // --- Facile (48 questions) ---
    {3,0,"Qui a écrit « Les Misérables » ?","Victor Hugo","Émile Zola","Balzac","Flaubert"},
    {3,0,"Qui a peint « La Joconde » ?","Léonard de Vinci","Michel-Ange","Raphaël","Botticelli"},
    {3,0,"Quel écrivain a créé Sherlock Holmes ?","Arthur Conan Doyle","Agatha Christie","Edgar Allan Poe","Maurice Leblanc"},
    {3,0,"Qui a peint « La Nuit étoilée » ?","Van Gogh","Monet","Cézanne","Gauguin"},
    {3,0,"Quel auteur a écrit « Le Petit Prince » ?","Saint-Exupéry","Camus","Proust","Gide"},
    {3,0,"Qui a sculpté « Le Penseur » ?","Rodin","Michel-Ange","Donatello","Bernini"},
    {3,0,"Quel roman commence par « Longtemps je me suis couché de bonne heure » ?","À la recherche du temps perdu","Madame Bovary","L'Étranger","Le Rouge et le Noir"},
    {3,0,"Qui a écrit « Roméo et Juliette » ?","Shakespeare","Molière","Corneille","Racine"},
    {3,0,"Quel peintre est célèbre pour ses nymphéas ?","Monet","Renoir","Degas","Manet"},
    {3,0,"Qui a écrit « L'Avare » ?","Molière","Racine","Corneille","Beaumarchais"},
    {3,0,"Quel mouvement artistique Picasso a-t-il cofondé ?","Le cubisme","Le surréalisme","L'impressionnisme","Le fauvisme"},
    {3,0,"Qui a écrit « 20 000 Lieues sous les mers » ?","Jules Verne","H.G. Wells","Alexandre Dumas","Victor Hugo"},
    {3,0,"Quel auteur a créé Hercule Poirot ?","Agatha Christie","Arthur Conan Doyle","Georges Simenon","Raymond Chandler"},
    {3,0,"Qui a peint « Le Cri » ?","Munch","Klimt","Kirchner","Nolde"},
    {3,0,"Quel philosophe a écrit « Le Mythe de Sisyphe » ?","Albert Camus","Sartre","Nietzsche","Kierkegaard"},
    {3,0,"Qui a écrit « Le Comte de Monte-Cristo » ?","Alexandre Dumas","Victor Hugo","Balzac","Stendhal"},
    {3,0,"Quel peintre a coupé son oreille ?","Van Gogh","Gauguin","Toulouse-Lautrec","Cézanne"},
    {3,0,"Qui a écrit « Madame Bovary » ?","Flaubert","Zola","Maupassant","Balzac"},
    {3,0,"Quel auteur a écrit « L'Odyssée » ?","Homère","Virgile","Ovide","Sophocle"},
    {3,0,"Qui a peint la chapelle Sixtine ?","Michel-Ange","Raphaël","Léonard de Vinci","Le Caravage"},
    {3,0,"Quel roman met en scène un certain Gatsby ?","Gatsby le Magnifique","Le Grand Gatsby","Gatsby","Les Hauts de Hurlevent"},
    {3,0,"Qui a écrit « Les Trois Mousquetaires » ?","Alexandre Dumas","Victor Hugo","Jules Verne","Balzac"},
    {3,0,"Quel peintre est connu pour ses montres molles ?","Dalí","Magritte","Ernst","Miró"},
    {3,0,"Qui a écrit « Le Rouge et le Noir » ?","Stendhal","Balzac","Flaubert","Zola"},
    {3,0,"Quel philosophe a dit « Je pense donc je suis » ?","Descartes","Kant","Hegel","Spinoza"},
    {3,0,"Qui a écrit « Germinal » ?","Émile Zola","Victor Hugo","Flaubert","Maupassant"},
    {3,0,"Quel auteur a créé le personnage de Don Quichotte ?","Cervantès","Shakespeare","Dante","Rabelais"},
    {3,0,"Qui a peint « Impression soleil levant » ?","Monet","Renoir","Pissarro","Sisley"},
    {3,0,"Quel écrivain a reçu le Nobel en 1957 ?","Albert Camus","Sartre","Gide","Mauriac"},
    {3,0,"Qui a écrit « Le Seigneur des Anneaux » ?","Tolkien","C.S. Lewis","Ursula Le Guin","Terry Pratchett"},
    {3,0,"Quel mouvement littéraire Baudelaire représente-t-il ?","Le symbolisme","Le romantisme","Le réalisme","Le naturalisme"},
    {3,0,"Qui a écrit « Crime et Châtiment » ?","Dostoïevski","Tolstoï","Tchekhov","Gogol"},
    {3,0,"Quel peintre a créé « Les Demoiselles d'Avignon » ?","Picasso","Matisse","Braque","Léger"},
    {3,0,"Qui a écrit « Le Vieil Homme et la Mer » ?","Hemingway","Faulkner","Steinbeck","Fitzgerald"},
    {3,0,"Quel auteur a écrit « Les Fleurs du Mal » ?","Baudelaire","Rimbaud","Verlaine","Mallarmé"},
    {3,0,"Qui a peint « La Liberté guidant le peuple » ?","Delacroix","David","Géricault","Ingres"},
    {3,0,"Quel philosophe a écrit « Ainsi parlait Zarathoustra » ?","Nietzsche","Schopenhauer","Kant","Hegel"},
    {3,0,"Qui a écrit « Guerre et Paix » ?","Tolstoï","Dostoïevski","Tchekhov","Pouchkine"},
    {3,0,"Quel auteur a créé le commissaire Maigret ?","Georges Simenon","Agatha Christie","Léo Malet","Fred Vargas"},
    {3,0,"Qui a peint « La Jeune Fille à la perle » ?","Vermeer","Rembrandt","Hals","Steen"},
    {3,0,"Quel écrivain a écrit « 1984 » ?","George Orwell","Aldous Huxley","Ray Bradbury","H.G. Wells"},
    {3,0,"Qui a écrit « Le Malade imaginaire » ?","Molière","Racine","Corneille","Marivaux"},
    {3,0,"Quel peintre est le père de l'impressionnisme ?","Monet","Manet","Renoir","Degas"},
    {3,0,"Qui a écrit « L'Étranger » ?","Albert Camus","Sartre","Gide","Mauriac"},
    {3,0,"Quel auteur a écrit « Ulysse » ?","James Joyce","Virginia Woolf","Marcel Proust","William Faulkner"},
    {3,0,"Qui a sculpté « Le David » ?","Michel-Ange","Donatello","Bernini","Les deux A et B"},
    {3,0,"Quel philosophe a écrit « Critique de la raison pure » ?","Kant","Hegel","Descartes","Spinoza"},
    {3,0,"Qui a écrit « Les Aventures de Tom Sawyer » ?","Mark Twain","Jack London","Hemingway","Steinbeck"},
    // --- Moyen (48 questions) ---
    {3,1,"Qui a écrit « Le Nom de la rose » ?","Umberto Eco","Italo Calvino","Dino Buzzati","Alberto Moravia"},
    {3,1,"Quel peintre a créé « Le Radeau de la Méduse » ?","Géricault","Delacroix","David","Ingres"},
    {3,1,"Qui a écrit « Cent Ans de solitude » ?","García Márquez","Vargas Llosa","Julio Cortázar","Carlos Fuentes"},
    {3,1,"Quel philosophe a développé l'existentialisme athée ?","Sartre","Camus","Heidegger","Kierkegaard"},
    {3,1,"Qui a peint « Guernica » ?","Picasso","Dalí","Miró","Gris"},
    {3,1,"Quel auteur a écrit « Le Procès » ?","Franz Kafka","Thomas Mann","Robert Musil","Hermann Hesse"},
    {3,1,"Qui a composé « Les Quatre Saisons » ?","Vivaldi","Bach","Haendel","Corelli"},
    {3,1,"Quel écrivain a créé le cycle de Dune ?","Frank Herbert","Isaac Asimov","Arthur C. Clarke","Philip K. Dick"},
    {3,1,"Qui a peint « La Persistance de la mémoire » ?","Dalí","Magritte","Ernst","Tanguy"},
    {3,1,"Quel philosophe a écrit « L'Être et le Néant » ?","Sartre","Heidegger","Merleau-Ponty","Camus"},
    {3,1,"Qui a écrit « Le Maître et Marguerite » ?","Boulgakov","Pasternak","Soljenitsyne","Nabokov"},
    {3,1,"Quel peintre a créé « Le Baiser » (1908) ?","Klimt","Schiele","Munch","Modigliani"},
    {3,1,"Qui a écrit « Le Tunnel » ?","Ernesto Sabato","Borges","Cortázar","Bioy Casares"},
    {3,1,"Quel compositeur a écrit « La Flûte enchantée » ?","Mozart","Beethoven","Wagner","Verdi"},
    {3,1,"Qui a peint « Le Déjeuner sur l'herbe » ?","Manet","Monet","Renoir","Cézanne"},
    {3,1,"Quel auteur a écrit « Le Château » ?","Franz Kafka","Thomas Mann","Musil","Hesse"},
    {3,1,"Qui a composé « Le Boléro » ?","Ravel","Debussy","Fauré","Satie"},
    {3,1,"Quel philosophe a écrit « Le Gai Savoir » ?","Nietzsche","Schopenhauer","Kierkegaard","Spinoza"},
    {3,1,"Qui a écrit « Le Docteur Jivago » ?","Pasternak","Boulgakov","Soljenitsyne","Cholokhov"},
    {3,1,"Quel peintre a créé « La Grande Vague de Kanagawa » ?","Hokusai","Hiroshige","Utamaro","Sharaku"},
    {3,1,"Qui a écrit « Fictions » ?","Borges","Cortázar","García Márquez","Neruda"},
    {3,1,"Quel compositeur a écrit « Tristan et Isolde » ?","Wagner","Verdi","Puccini","Strauss"},
    {3,1,"Qui a peint « Olympia » ?","Manet","Monet","Courbet","Degas"},
    {3,1,"Quel auteur a écrit « Le Désert des Tartares » ?","Dino Buzzati","Italo Calvino","Primo Levi","Cesare Pavese"},
    {3,1,"Qui a composé « Le Lac des cygnes » ?","Tchaïkovski","Stravinsky","Prokofiev","Rimski-Korsakov"},
    {3,1,"Quel philosophe a écrit « Phénoménologie de l'esprit » ?","Hegel","Kant","Husserl","Heidegger"},
    {3,1,"Qui a écrit « Le Tambour » ?","Günter Grass","Heinrich Böll","Thomas Mann","Hermann Hesse"},
    {3,1,"Quel peintre a créé « Les Joueurs de cartes » ?","Cézanne","Monet","Renoir","Manet"},
    {3,1,"Qui a écrit « La Peste » ?","Albert Camus","Sartre","Gide","Mauriac"},
    {3,1,"Quel compositeur a écrit « Carmen » ?","Bizet","Gounod","Massenet","Saint-Saëns"},
    {3,1,"Qui a peint « Le Jardin des délices » ?","Jérôme Bosch","Brueghel","Van Eyck","Memling"},
    {3,1,"Quel auteur a écrit « Le Parfum » ?","Patrick Süskind","Thomas Mann","Hermann Hesse","Günter Grass"},
    {3,1,"Qui a composé « Le Messie » ?","Haendel","Bach","Vivaldi","Purcell"},
    {3,1,"Quel philosophe a écrit « Le Contrat social » ?","Rousseau","Voltaire","Montesquieu","Diderot"},
    {3,1,"Qui a écrit « Lolita » ?","Nabokov","Pasternak","Boulgakov","Soljenitsyne"},
    {3,1,"Quel peintre a créé « Le Fils de l'homme » ?","Magritte","Dalí","Ernst","Tanguy"},
    {3,1,"Qui a écrit « Le Grand Meaulnes » ?","Alain-Fournier","Proust","Gide","Mauriac"},
    {3,1,"Quel compositeur a écrit « La Chevauchée des Walkyries » ?","Wagner","Verdi","Strauss","Brahms"},
    {3,1,"Qui a peint « L'École d'Athènes » ?","Raphaël","Michel-Ange","Léonard de Vinci","Le Pérugin"},
    {3,1,"Quel auteur a écrit « Le Bateau ivre » ?","Rimbaud","Verlaine","Baudelaire","Mallarmé"},
    {3,1,"Qui a composé « La Symphonie du Nouveau Monde » ?","Dvořák","Smetana","Brahms","Mahler"},
    {3,1,"Quel philosophe a écrit « Les Mots et les Choses » ?","Foucault","Derrida","Deleuze","Bourdieu"},
    {3,1,"Qui a écrit « Le Rivage des Syrtes » ?","Julien Gracq","André Breton","Paul Éluard","Louis Aragon"},
    {3,1,"Quel peintre a créé « La Ronde de nuit » ?","Rembrandt","Vermeer","Hals","Rubens"},
    {3,1,"Qui a écrit « L'Usage du monde » ?","Nicolas Bouvier","Bruce Chatwin","Paul Theroux","Jack Kerouac"},
    {3,1,"Quel compositeur a écrit « Le Sacre du printemps » ?","Stravinsky","Debussy","Ravel","Bartók"},
    {3,1,"Qui a peint « Les Tournesols » ?","Van Gogh","Monet","Gauguin","Cézanne"},
    {3,1,"Quel auteur a écrit « Le Horla » ?","Maupassant","Zola","Flaubert","Balzac"},
    // --- Difficile (24 questions) ---
    {3,2,"Qui a écrit « L'Homme sans qualités » ?","Robert Musil","Thomas Mann","Hermann Broch","Joseph Roth"},
    {3,2,"Quel peintre a créé « L'Origine du monde » ?","Courbet","Manet","Delacroix","Ingres"},
    {3,2,"Qui a écrit « La Montagne magique » ?","Thomas Mann","Hermann Hesse","Robert Musil","Stefan Zweig"},
    {3,2,"Quel philosophe a écrit « Différence et Répétition » ?","Gilles Deleuze","Jacques Derrida","Michel Foucault","Lyotard"},
    {3,2,"Qui a composé « Gaspard de la nuit » ?","Ravel","Debussy","Satie","Fauré"},
    {3,2,"Quel peintre a créé « Le Cri » (version originale 1893) ?","Munch","Kirchner","Nolde","Kokoschka"},
    {3,2,"Qui a écrit « La Vie mode d'emploi » ?","Georges Perec","Raymond Queneau","Italo Calvino","Boris Vian"},
    {3,2,"Quel philosophe a écrit « Totalité et Infini » ?","Emmanuel Levinas","Paul Ricœur","Merleau-Ponty","Sartre"},
    {3,2,"Qui a composé « Le Marteau sans maître » ?","Pierre Boulez","Olivier Messiaen","Edgard Varèse","Xenakis"},
    {3,2,"Quel peintre a créé « Les Ménines » ?","Vélasquez","Goya","Le Greco","Murillo"},
    {3,2,"Qui a écrit « Le Livre de l'inquiétude » ?","Fernando Pessoa","José Saramago","Eça de Queirós","Miguel Torga"},
    {3,2,"Quel philosophe a écrit « L'Envers et l'Endroit » ?","Albert Camus","Sartre","Merleau-Ponty","Simone de Beauvoir"},
    {3,2,"Qui a composé « Ionisation » ?","Edgard Varèse","Pierre Boulez","Iannis Xenakis","Stockhausen"},
    {3,2,"Quel peintre a créé « Le Jardin des délices terrestres » ?","Jérôme Bosch","Pieter Brueghel","Jan van Eyck","Hans Memling"},
    {3,2,"Qui a écrit « Le Ravissement de Lol V. Stein » ?","Marguerite Duras","Nathalie Sarraute","Claude Simon","Robbe-Grillet"},
    {3,2,"Quel philosophe a écrit « Phénoménologie de la perception » ?","Merleau-Ponty","Husserl","Heidegger","Sartre"},
    {3,2,"Qui a composé « Déserts » ?","Edgard Varèse","Pierre Schaeffer","Pierre Henry","Luc Ferrari"},
    {3,2,"Quel peintre a créé « La Flagellation du Christ » ?","Piero della Francesca","Le Caravage","Giotto","Masaccio"},
    {3,2,"Qui a écrit « Molloy » ?","Samuel Beckett","James Joyce","Eugène Ionesco","Jean Genet"},
    {3,2,"Quel philosophe a écrit « De la grammatologie » ?","Jacques Derrida","Gilles Deleuze","Michel Foucault","Levinas"},
    {3,2,"Qui a composé « Répons » ?","Pierre Boulez","Olivier Messiaen","György Ligeti","Stockhausen"},
    {3,2,"Quel peintre a créé « L'Annonciation » (1472) ?","Léonard de Vinci","Fra Angelico","Botticelli","Le Pérugin"},
    {3,2,"Qui a écrit « La Jalousie » ?","Alain Robbe-Grillet","Nathalie Sarraute","Claude Simon","Michel Butor"},
    {3,2,"Quel philosophe a écrit « Logique du sens » ?","Gilles Deleuze","Jacques Derrida","Michel Foucault","Lyotard"},
};

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIE 4 : SCIENCES & NATURE (Vert) — physique, bio, tech, espace
// ═══════════════════════════════════════════════════════════════════════════════
static const TriviaQuestion QUESTIONS_SCI[TRIVIA_Q_SCI] = {
    // --- Facile (48 questions) ---
    {4,0,"Quelle est la formule chimique de l'eau ?","H2O","CO2","NaCl","O2"},
    {4,0,"Quelle planète est la plus proche du Soleil ?","Mercure","Vénus","Mars","La Terre"},
    {4,0,"Combien d'os compte le corps humain adulte ?","206","212","198","220"},
    {4,0,"Quel gaz les plantes absorbent-elles ?","Le CO2","L'oxygène","L'azote","L'hydrogène"},
    {4,0,"Quelle est la vitesse de la lumière ?","300 000 km/s","150 000 km/s","1 000 000 km/s","30 000 km/s"},
    {4,0,"Quel organe pompe le sang ?","Le cœur","Le foie","Les poumons","Les reins"},
    {4,0,"Quelle est la plus grande planète du système solaire ?","Jupiter","Saturne","Neptune","Uranus"},
    {4,0,"Quel élément chimique a pour symbole O ?","L'oxygène","L'or","L'osmium","L'oganesson"},
    {4,0,"Combien de chromosomes possède l'humain ?","46","44","48","42"},
    {4,0,"Quel animal est le plus rapide au monde ?","Le guépard","Le faucon pèlerin","L'antilope","Le lévrier"},
    {4,0,"Quelle est l'unité de mesure de la force ?","Le newton","Le joule","Le watt","Le pascal"},
    {4,0,"Quel organe produit l'insuline ?","Le pancréas","Le foie","Les reins","La rate"},
    {4,0,"Quelle planète est surnommée « la planète rouge » ?","Mars","Vénus","Jupiter","Mercure"},
    {4,0,"Quel gaz est essentiel à la respiration humaine ?","L'oxygène","L'azote","Le CO2","L'hélium"},
    {4,0,"Combien de planètes compte le système solaire ?","8","9","7","10"},
    {4,0,"Quel est le métal le plus conducteur ?","L'argent","Le cuivre","L'or","L'aluminium"},
    {4,0,"Quel animal est le plus grand mammifère ?","La baleine bleue","L'éléphant","La girafe","L'hippopotame"},
    {4,0,"Quelle est l'unité de mesure de l'énergie ?","Le joule","Le watt","Le volt","L'ampère"},
    {4,0,"Quel organe filtre le sang ?","Les reins","Le foie","La rate","Le pancréas"},
    {4,0,"Quelle est la température d'ébullition de l'eau ?","100 °C","90 °C","110 °C","80 °C"},
    {4,0,"Quel est le plus petit os du corps humain ?","L'étrier","Le marteau","L'enclume","Le radius"},
    {4,0,"Quelle planète possède les anneaux les plus visibles ?","Saturne","Jupiter","Uranus","Neptune"},
    {4,0,"Quel élément est le plus abondant dans l'univers ?","L'hydrogène","L'hélium","L'oxygène","Le carbone"},
    {4,0,"Combien de pattes a une araignée ?","8","6","10","12"},
    {4,0,"Quel est le symbole chimique du fer ?","Fe","Fr","Fi","F"},
    {4,0,"Quel organe permet de respirer ?","Les poumons","Le cœur","Le foie","Les reins"},
    {4,0,"Quelle est la distance Terre-Soleil environ ?","150 millions km","100 millions km","200 millions km","50 millions km"},
    {4,0,"Quel animal pond des œufs et allaite ?","L'ornithorynque","Le kangourou","Le koala","Le tatou"},
    {4,0,"Quelle est l'unité de mesure de la puissance ?","Le watt","Le joule","Le volt","L'ohm"},
    {4,0,"Quel gaz provoque l'effet de serre principal ?","Le CO2","L'oxygène","L'azote","L'hélium"},
    {4,0,"Combien de dents a un adulte ?","32","28","30","36"},
    {4,0,"Quel est le plus grand organe du corps humain ?","La peau","Le foie","Les poumons","L'intestin"},
    {4,0,"Quelle planète tourne sur le côté ?","Uranus","Neptune","Saturne","Mars"},
    {4,0,"Quel élément chimique a pour symbole Na ?","Le sodium","Le néon","L'azote","Le nickel"},
    {4,0,"Quel animal peut régénérer ses membres ?","La salamandre","Le lézard","L'étoile de mer","Les deux A et C"},
    {4,0,"Quelle est l'unité de mesure de la résistance ?","L'ohm","Le volt","L'ampère","Le watt"},
    {4,0,"Quel est le plus grand désert du monde ?","L'Antarctique","Le Sahara","Le Gobi","L'Arctique"},
    {4,0,"Combien de cœurs a une pieuvre ?","3","1","2","4"},
    {4,0,"Quel est le symbole chimique de l'or ?","Au","Ag","Or","Go"},
    {4,0,"Quel organe produit la bile ?","Le foie","Le pancréas","La vésicule","L'estomac"},
    {4,0,"Quelle est la planète la plus chaude ?","Vénus","Mercure","Mars","Jupiter"},
    {4,0,"Quel animal a le plus long cou ?","La girafe","L'autruche","Le cygne","Le lama"},
    {4,0,"Quelle est l'unité de mesure de la tension ?","Le volt","L'ampère","Le watt","L'ohm"},
    {4,0,"Quel est le plus petit planète du système solaire ?","Mercure","Mars","Pluton","Vénus"},
    {4,0,"Combien de litres de sang contient le corps humain ?","5 litres","3 litres","7 litres","10 litres"},
    {4,0,"Quel gaz est produit par la photosynthèse ?","L'oxygène","Le CO2","L'azote","L'hydrogène"},
    {4,0,"Quel est le symbole chimique du carbone ?","C","Ca","Cr","Co"},
    {4,0,"Quel animal dort le plus longtemps ?","Le koala","Le paresseux","Le chat","La marmotte"},
    // --- Moyen (48 questions) ---
    {4,1,"Quel scientifique a formulé la théorie de la relativité ?","Einstein","Newton","Bohr","Hawking"},
    {4,1,"Quel est le numéro atomique du carbone ?","6","8","12","14"},
    {4,1,"Quel est le plus grand satellite naturel de Saturne ?","Titan","Encelade","Rhéa","Japet"},
    {4,1,"Quel scientifique a découvert la pénicilline ?","Alexander Fleming","Louis Pasteur","Robert Koch","Joseph Lister"},
    {4,1,"Quel est le pH de l'eau pure ?","7","6","8","7,4"},
    {4,1,"Quel est le plus long os du corps humain ?","Le fémur","Le tibia","L'humérus","Le radius"},
    {4,1,"Quel scientifique a proposé la théorie de l'évolution ?","Charles Darwin","Lamarck","Mendel","Wallace"},
    {4,1,"Quel est le symbole chimique du potassium ?","K","Po","Pt","P"},
    {4,1,"Quelle est la durée de vie moyenne d'un globule rouge ?","120 jours","60 jours","200 jours","30 jours"},
    {4,1,"Quel est le plus grand volcan du système solaire ?","Olympus Mons","Le Vésuve","L'Etna","Le Mauna Kea"},
    {4,1,"Quel scientifique a découvert la radioactivité ?","Henri Becquerel","Marie Curie","Pierre Curie","Rutherford"},
    {4,1,"Quel est le symbole chimique du mercure ?","Hg","Me","Mr","M"},
    {4,1,"Combien de paires de chromosomes possède l'humain ?","23","22","24","21"},
    {4,1,"Quel est le plus petit planète naine reconnue ?","Cérès","Pluton","Éris","Makémaké"},
    {4,1,"Quel scientifique a formulé les lois du mouvement ?","Newton","Galilée","Kepler","Einstein"},
    {4,1,"Quel est le symbole chimique de l'étain ?","Sn","Et","Ti","Sb"},
    {4,1,"Quelle est la durée de vie moyenne d'un globule blanc ?","Quelques jours","120 jours","1 an","10 ans"},
    {4,1,"Quel est le plus grand océan de la Terre ?","Le Pacifique","L'Atlantique","L'Indien","L'Arctique"},
    {4,1,"Quel scientifique a découvert la structure de l'ADN ?","Watson et Crick","Mendel","Pasteur","Darwin"},
    {4,1,"Quel est le symbole chimique du tungstène ?","W","Tu","Tg","Wt"},
    {4,1,"Combien de vertèbres a la colonne vertébrale humaine ?","33","30","36","28"},
    {4,1,"Quel est le plus grand satellite de Jupiter ?","Ganymède","Callisto","Io","Europe"},
    {4,1,"Quel scientifique a formulé la théorie de la gravitation ?","Newton","Einstein","Galilée","Kepler"},
    {4,1,"Quel est le symbole chimique du plomb ?","Pb","Pl","Ld","P"},
    {4,1,"Quelle est la température du corps humain normal ?","37 °C","36 °C","38 °C","39 °C"},
    {4,1,"Quel est le plus grand mammifère terrestre ?","L'éléphant d'Afrique","La girafe","L'hippopotame","Le rhinocéros"},
    {4,1,"Quel scientifique a découvert les lois de l'hérédité ?","Mendel","Darwin","Pasteur","Lamarck"},
    {4,1,"Quel est le symbole chimique de l'argent ?","Ag","Ar","Au","An"},
    {4,1,"Combien de muscles compte le corps humain environ ?","600","400","800","1000"},
    {4,1,"Quel est le plus profond océan de la Terre ?","Le Pacifique","L'Atlantique","L'Indien","L'Arctique"},
    {4,1,"Quel scientifique a formulé le principe d'incertitude ?","Heisenberg","Bohr","Schrödinger","Dirac"},
    {4,1,"Quel est le symbole chimique du cuivre ?","Cu","Co","Cp","Cr"},
    {4,1,"Quelle est la durée de gestation d'un éléphant ?","22 mois","12 mois","18 mois","9 mois"},
    {4,1,"Quel est le plus grand reptile du monde ?","Le crocodile marin","Le python","Le varan de Komodo","L'anaconda"},
    {4,1,"Quel scientifique a découvert la loi de la gravitation universelle ?","Newton","Einstein","Galilée","Kepler"},
    {4,1,"Quel est le symbole chimique du zinc ?","Zn","Zi","Zc","Z"},
    {4,1,"Combien de neurones possède le cerveau humain environ ?","86 milliards","100 milliards","50 milliards","10 milliards"},
    {4,1,"Quel est le plus grand oiseau du monde ?","L'autruche","Le condor","L'albatros","L'émeu"},
    {4,1,"Quel scientifique a formulé la théorie du Big Bang ?","Georges Lemaître","Einstein","Hubble","Gamow"},
    {4,1,"Quel est le symbole chimique du brome ?","Br","Bo","Bm","B"},
    {4,1,"Quelle est la durée de vie moyenne d'une mouche ?","Quelques semaines","1 jour","1 mois","1 an"},
    {4,1,"Quel est le plus grand poisson du monde ?","Le requin-baleine","La baleine bleue","Le requin blanc","Le poisson-lune"},
    {4,1,"Quel scientifique a découvert la loi de la sélection naturelle ?","Darwin","Lamarck","Mendel","Wallace"},
    {4,1,"Quel est le symbole chimique du sélénium ?","Se","Sl","Sn","S"},
    {4,1,"Combien de litres d'air respire un humain par jour ?","10 000 litres","5 000 litres","20 000 litres","1 000 litres"},
    {4,1,"Quel est le plus grand insecte du monde ?","Le phasme","Le scarabée Goliath","Le papillon Atlas","La mante"},
    {4,1,"Quel scientifique a formulé la théorie de la relativité restreinte ?","Einstein","Newton","Bohr","Maxwell"},
    {4,1,"Quel est le symbole chimique du manganèse ?","Mn","Ma","Mg","M"},
    // --- Difficile (24 questions) ---
    {4,2,"Quel est le numéro atomique de l'uranium ?","92","90","94","88"},
    {4,2,"Quel scientifique a découvert le boson de Higgs ?","Peter Higgs","François Englert","Les deux A et B","CERN"},
    {4,2,"Quel est le plus ancien organisme vivant connu ?","Le pin de Bristlecone","Le séquoia","Le baobab","L'if"},
    {4,2,"Quel est le symbole chimique du césium ?","Cs","Ce","Cm","C"},
    {4,2,"Quel scientifique a formulé la théorie des cordes ?","Plusieurs physiciens","Einstein","Hawking","Feynman"},
    {4,2,"Quel est le plus petit mammifère du monde ?","Le pachyure étrusque","La musaraigne","Le colibri","Le hamster nain"},
    {4,2,"Quel est le numéro atomique de l'hélium ?","2","1","3","4"},
    {4,2,"Quel scientifique a découvert la fission nucléaire ?","Otto Hahn","Enrico Fermi","Lise Meitner","Les deux A et C"},
    {4,2,"Quel est le plus ancien fossile humain connu ?","Toumaï","Lucy","L'homme de Néandertal","L'homme de Cro-Magnon"},
    {4,2,"Quel est le symbole chimique du rhodium ?","Rh","Ro","Rd","R"},
    {4,2,"Quel scientifique a formulé la théorie quantique des champs ?","Plusieurs physiciens","Einstein","Bohr","Feynman"},
    {4,2,"Quel est le plus grand organisme vivant du monde ?","Le champignon Armillaria","La baleine bleue","Le séquoia","La Grande Barrière"},
    {4,2,"Quel est le numéro atomique du plutonium ?","94","92","96","90"},
    {4,2,"Quel scientifique a découvert la supraconductivité ?","Heike Kamerlingh Onnes","Meissner","Bardeen","Cooper"},
    {4,2,"Quel est le plus ancien arbre vivant connu ?","Mathusalem","Le général Sherman","Le Major Oak","Le Jōmon Sugi"},
    {4,2,"Quel est le symbole chimique du dysprosium ?","Dy","Dp","Ds","D"},
    {4,2,"Quel scientifique a formulé la théorie de la relativité générale ?","Einstein","Newton","Hilbert","Minkowski"},
    {4,2,"Quel est le plus petit oiseau du monde ?","Le colibri d'Elena","Le roitelet","Le troglodyte","Le colibri abeille"},
    {4,2,"Quel est le numéro atomique du francium ?","87","85","89","83"},
    {4,2,"Quel scientifique a découvert la radioactivité artificielle ?","Irène et Frédéric Joliot-Curie","Marie Curie","Becquerel","Rutherford"},
    {4,2,"Quel est le plus ancien minéral connu sur Terre ?","Le zircon","Le quartz","Le diamant","Le feldspath"},
    {4,2,"Quel est le symbole chimique du nobélium ?","No","Nb","Nl","N"},
    {4,2,"Quel scientifique a formulé la théorie de l'inflation cosmique ?","Alan Guth","Andrei Linde","Les deux A et B","Hawking"},
    {4,2,"Quel est le plus grand virus connu ?","Le pandoravirus","Le mimivirus","Le mégavirus","Le pithovirus"},
};

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIE 5 : SPORTS & LOISIRS (Orange) — sport, cuisine, vie pratique
// ═══════════════════════════════════════════════════════════════════════════════
static const TriviaQuestion QUESTIONS_SPO[TRIVIA_Q_SPO] = {
    // --- Facile (48 questions) ---
    {5,0,"Combien de joueurs dans une équipe de football ?","11","10","12","9"},
    {5,0,"Quel sport se joue avec un volant ?","Le badminton","Le tennis","Le squash","Le ping-pong"},
    {5,0,"Combien de temps dure un match de football ?","90 minutes","80 minutes","100 minutes","60 minutes"},
    {5,0,"Quel pays a gagné la Coupe du monde 2018 ?","La France","La Croatie","La Belgique","Le Brésil"},
    {5,0,"Quel sport utilise un panier ?","Le basket-ball","Le volley-ball","Le handball","Le rugby"},
    {5,0,"Combien de sets pour gagner un match de tennis masculin ?","3","2","4","5"},
    {5,0,"Quel pays a inventé le judo ?","Le Japon","La Chine","La Corée","La Thaïlande"},
    {5,0,"Quel sport se pratique sur un ring ?","La boxe","Le judo","La lutte","Le karaté"},
    {5,0,"Combien de joueurs dans une équipe de rugby à XV ?","15","13","11","14"},
    {5,0,"Quel pays a gagné le plus de Coupes du monde de football ?","Le Brésil","L'Allemagne","L'Italie","L'Argentine"},
    {5,0,"Quel sport utilise un club et une balle ?","Le golf","Le tennis","Le cricket","Le base-ball"},
    {5,0,"Combien de mètres fait une piscine olympique ?","50 mètres","25 mètres","100 mètres","33 mètres"},
    {5,0,"Quel pays a inventé le cricket ?","L'Angleterre","L'Australie","L'Inde","L'Afrique du Sud"},
    {5,0,"Quel sport se pratique avec un ballon ovale ?","Le rugby","Le football","Le basket","Le volley"},
    {5,0,"Combien de points vaut un essai au rugby ?","5","3","7","4"},
    {5,0,"Quel pays a gagné Roland-Garros le plus souvent ?","L'Espagne","La France","Les États-Unis","L'Australie"},
    {5,0,"Quel sport utilise une raquette et un volant ?","Le badminton","Le tennis","Le squash","Le padel"},
    {5,0,"Combien de joueurs dans une équipe de volley-ball ?","6","5","7","8"},
    {5,0,"Quel pays a inventé le sumo ?","Le Japon","La Chine","La Mongolie","La Corée"},
    {5,0,"Quel sport se pratique sur un court en terre battue ?","Le tennis","Le badminton","Le squash","Le padel"},
    {5,0,"Combien de minutes dure un match de basket NBA ?","48 minutes","40 minutes","45 minutes","50 minutes"},
    {5,0,"Quel pays a gagné le plus de médailles olympiques ?","Les États-Unis","La Russie","La Chine","L'Allemagne"},
    {5,0,"Quel sport utilise un arc et des flèches ?","Le tir à l'arc","Le javelot","Le lancer de disque","Le biathlon"},
    {5,0,"Combien de trous dans un parcours de golf standard ?","18","9","27","12"},
    {5,0,"Quel pays a inventé le taekwondo ?","La Corée du Sud","Le Japon","La Chine","Le Viêt Nam"},
    {5,0,"Quel sport se pratique dans une piscine ?","La natation","Le water-polo","Les deux A et B","Le plongeon"},
    {5,0,"Combien de joueurs dans une équipe de handball ?","7","6","8","5"},
    {5,0,"Quel pays a gagné la Coupe du monde 2022 ?","L'Argentine","La France","Le Brésil","La Croatie"},
    {5,0,"Quel sport utilise un ballon et un filet haut ?","Le volley-ball","Le tennis","Le badminton","Le basket"},
    {5,0,"Combien de kilomètres fait un marathon ?","42,195 km","40 km","45 km","38 km"},
    {5,0,"Quel pays a inventé le karaté ?","Le Japon","La Chine","La Corée","Okinawa"},
    {5,0,"Quel sport se pratique avec des patins sur glace ?","Le patinage artistique","Le hockey","Les deux A et B","Le curling"},
    {5,0,"Combien de points vaut un panier à 3 points ?","3","2","4","1"},
    {5,0,"Quel pays a gagné le plus de Tour de France ?","La France","La Belgique","L'Espagne","L'Italie"},
    {5,0,"Quel sport utilise une balle et une batte ?","Le base-ball","Le cricket","Les deux A et B","Le golf"},
    {5,0,"Combien de joueurs dans une équipe de water-polo ?","7","6","8","5"},
    {5,0,"Quel pays a inventé le ping-pong ?","L'Angleterre","La Chine","Le Japon","La Corée"},
    {5,0,"Quel sport se pratique avec un ballon et des pieds ?","Le football","Le rugby","Le futsal","Les deux A et C"},
    {5,0,"Combien de minutes dure une mi-temps de football ?","45 minutes","40 minutes","50 minutes","30 minutes"},
    {5,0,"Quel pays a gagné le plus de Jeux olympiques d'été ?","Les États-Unis","La Russie","La Chine","L'Allemagne"},
    {5,0,"Quel sport utilise un ballon et un but ?","Le football","Le handball","Le hockey","Tous ces sports"},
    {5,0,"Combien de sets pour gagner un match de volley-ball ?","3","2","4","5"},
    {5,0,"Quel pays a inventé le curling ?","L'Écosse","Le Canada","La Suisse","La Suède"},
    {5,0,"Quel sport se pratique avec un ballon et un panier ?","Le basket-ball","Le volley-ball","Le handball","Le rugby"},
    {5,0,"Combien de points vaut un but au football ?","1","2","3","0,5"},
    {5,0,"Quel pays a gagné le plus de Coupes du monde de rugby ?","La Nouvelle-Zélande","L'Afrique du Sud","L'Australie","L'Angleterre"},
    {5,0,"Quel sport utilise un ballon et une raquette ?","Le tennis","Le badminton","Le squash","Aucun de ces sports"},
    {5,0,"Combien de joueurs dans une équipe de futsal ?","5","6","7","4"},
    // --- Moyen (48 questions) ---
    {5,1,"Quel joueur a marqué le plus de buts en Coupe du monde ?","Miroslav Klose","Ronaldo","Pelé","Gerd Müller"},
    {5,1,"Quel pays a inventé le hockey sur glace ?","Le Canada","La Russie","La Suède","Les États-Unis"},
    {5,1,"Combien de Grand Chelems Roger Federer a-t-il gagnés ?","20","18","22","17"},
    {5,1,"Quel sport utilise un volant en plumes ?","Le badminton","Le tennis","Le squash","Le padel"},
    {5,1,"Quel pays a gagné le premier Tour de France ?","La France","La Belgique","L'Italie","L'Espagne"},
    {5,1,"Combien de points vaut un drop au rugby ?","3","5","7","2"},
    {5,1,"Quel joueur a gagné le plus de Ballons d'or ?","Lionel Messi","Cristiano Ronaldo","Michel Platini","Johan Cruyff"},
    {5,1,"Quel sport se pratique avec un ballon et un bouclier ?","Aucun sport standard","Le rugby","Le football américain","Le hockey"},
    {5,1,"Quel pays a inventé le volleyball ?","Les États-Unis","Le Brésil","Le Japon","L'Italie"},
    {5,1,"Combien de minutes dure un match de rugby ?","80 minutes","90 minutes","70 minutes","60 minutes"},
    {5,1,"Quel nageur a gagné le plus de médailles olympiques ?","Michael Phelps","Mark Spitz","Ryan Lochte","Ian Thorpe"},
    {5,1,"Quel sport utilise un ballon et un filet bas ?","Le tennis","Le volley-ball","Le badminton","Le ping-pong"},
    {5,1,"Quel pays a gagné le plus de Coupes Davis ?","Les États-Unis","L'Australie","La France","L'Espagne"},
    {5,1,"Combien de joueurs dans une équipe de cricket ?","11","10","12","9"},
    {5,1,"Quel athlète a couru le 100 m en 9,58 s ?","Usain Bolt","Carl Lewis","Justin Gatlin","Tyson Gay"},
    {5,1,"Quel sport se pratique avec un ballon et des crosses ?","Le hockey sur gazon","Le football","Le rugby","Le cricket"},
    {5,1,"Quel pays a inventé le basketball ?","Les États-Unis","Le Canada","L'Angleterre","La France"},
    {5,1,"Combien de points vaut un panier en basket ?","2 ou 3","1 ou 2","2 uniquement","3 uniquement"},
    {5,1,"Quel joueur a marqué le plus de buts en Ligue 1 ?","Delio Onnis","Hervé Revelli","Bernard Lacombe","Jean-Pierre Papin"},
    {5,1,"Quel sport utilise un ballon et un marteau ?","Aucun sport standard","Le cricket","Le polo","Le hurling"},
    {5,1,"Quel pays a gagné le plus de Coupes du monde de cricket ?","L'Australie","L'Angleterre","L'Inde","Les Indes occidentales"},
    {5,1,"Combien de trous dans un parcours de golf miniature ?","18","9","12","27"},
    {5,1,"Quel cycliste a gagné le plus de Tours de France ?","Jacques Anquetil et 4 autres","Lance Armstrong","Eddy Merckx","Miguel Indurain"},
    {5,1,"Quel sport se pratique avec un ballon et un arc ?","Aucun sport standard","Le tir à l'arc","Le football","Le rugby"},
    {5,1,"Quel pays a inventé le rugby ?","L'Angleterre","L'Écosse","Le pays de Galles","L'Irlande"},
    {5,1,"Combien de points vaut un essai transformé au rugby ?","7","5","3","6"},
    {5,1,"Quel tennisman a gagné le plus de Roland-Garros ?","Rafael Nadal","Björn Borg","Gustavo Kuerten","Ivan Lendl"},
    {5,1,"Quel sport utilise un ballon et un gant ?","Le base-ball","Le cricket","Le handball","Le football américain"},
    {5,1,"Quel pays a gagné le plus de médailles en natation ?","Les États-Unis","L'Australie","La Russie","L'Allemagne"},
    {5,1,"Combien de joueurs dans une équipe de hockey sur glace ?","6","5","7","8"},
    {5,1,"Quel boxeur a été surnommé « The Greatest » ?","Mohamed Ali","Mike Tyson","Joe Frazier","George Foreman"},
    {5,1,"Quel sport se pratique avec un ballon et un filet haut ?","Le volley-ball","Le tennis","Le badminton","Le basket"},
    {5,1,"Quel pays a inventé le handball ?","L'Allemagne","Le Danemark","La Suède","La France"},
    {5,1,"Combien de points vaut un field goal au football américain ?","3","6","7","2"},
    {5,1,"Quel footballeur a gagné le plus de Ligues des champions ?","Francisco Gento","Paolo Maldini","Cristiano Ronaldo","Lionel Messi"},
    {5,1,"Quel sport utilise un ballon et un casque ?","Le football américain","Le hockey","Le cricket","Le rugby"},
    {5,1,"Quel pays a gagné le plus de Coupes du monde de hockey ?","Le Canada","La Russie","La Suède","La Tchéquie"},
    {5,1,"Combien de minutes dure un match de hockey sur glace ?","60 minutes","80 minutes","90 minutes","48 minutes"},
    {5,1,"Quel golfeur a gagné le plus de Masters ?","Jack Nicklaus","Tiger Woods","Arnold Palmer","Gary Player"},
    {5,1,"Quel sport se pratique avec un ballon et un bouclier ?","Aucun sport standard","Le rugby","Le football américain","Le hockey"},
    {5,1,"Quel pays a inventé le badminton ?","L'Angleterre","L'Inde","La Chine","Le Japon"},
    {5,1,"Combien de points vaut un touchdown au football américain ?","6","7","3","2"},
    {5,1,"Quel athlète a sauté le plus haut en hauteur ?","Javier Sotomayor","Mutaz Essa Barshim","Patrik Sjöberg","Charles Austin"},
    {5,1,"Quel sport utilise un ballon et un filet bas ?","Le tennis","Le volley-ball","Le badminton","Le ping-pong"},
    {5,1,"Quel pays a gagné le plus de Coupes du monde de basket ?","Les États-Unis","La Yougoslavie","L'URSS","L'Espagne"},
    {5,1,"Combien de joueurs dans une équipe de football américain ?","11","10","12","9"},
    {5,1,"Quel cycliste a gagné le plus de étapes du Tour ?","Eddy Merckx","Bernard Hinault","Lance Armstrong","Miguel Indurain"},
    {5,1,"Quel sport se pratique avec un ballon et un arc ?","Aucun sport standard","Le tir à l'arc","Le football","Le rugby"},
    // --- Difficile (24 questions) ---
    {5,2,"Quel pays a inventé le polo ?","La Perse (Iran)","L'Inde","L'Angleterre","L'Argentine"},
    {5,2,"Combien de Grand Chelems Margaret Court a-t-elle gagnés ?","24","22","20","18"},
    {5,2,"Quel sport utilise un ballon et un maillet ?","Le polo","Le cricket","Le hockey","Le croquet"},
    {5,2,"Quel pays a gagné le premier match de cricket international ?","L'Australie","L'Angleterre","L'Afrique du Sud","Les Indes occidentales"},
    {5,2,"Combien de points vaut un safety au football américain ?","2","3","6","1"},
    {5,2,"Quel athlète a couru le marathon en moins de 2 heures ?","Eliud Kipchoge","Kenenisa Bekele","Haile Gebrselassie","Dennis Kimetto"},
    {5,2,"Quel sport se pratique avec un ballon et un filet haut ?","Le volley-ball","Le tennis","Le badminton","Le basket"},
    {5,2,"Quel pays a inventé le sepak takraw ?","La Thaïlande","La Malaisie","L'Indonésie","Les Philippines"},
    {5,2,"Combien de joueurs dans une équipe de kabaddi ?","7","6","8","5"},
    {5,2,"Quel boxeur a été champion du monde dans 8 catégories ?","Manny Pacquiao","Floyd Mayweather","Oscar De La Hoya","Sugar Ray Leonard"},
    {5,2,"Quel sport utilise un ballon et un bouclier ?","Aucun sport standard","Le rugby","Le football américain","Le hockey"},
    {5,2,"Quel pays a gagné le plus de Coupes du monde de polo ?","L'Argentine","Les États-Unis","L'Angleterre","L'Inde"},
    {5,2,"Combien de points vaut un essai au rugby à XIII ?","4","5","3","6"},
    {5,2,"Quel athlète a lancé le javelot le plus loin ?","Jan Železný","Johannes Vetter","Thomas Röhler","Andreas Thorkildsen"},
    {5,2,"Quel sport se pratique avec un ballon et un arc ?","Aucun sport standard","Le tir à l'arc","Le football","Le rugby"},
    {5,2,"Quel pays a inventé le hurling ?","L'Irlande","L'Écosse","Le pays de Galles","L'Angleterre"},
    {5,2,"Combien de joueurs dans une équipe de rugby à VII ?","7","6","8","5"},
    {5,2,"Quel nageur a gagné le plus de médailles d'or olympiques ?","Michael Phelps","Mark Spitz","Ryan Lochte","Ian Thorpe"},
    {5,2,"Quel sport utilise un ballon et un marteau ?","Aucun sport standard","Le cricket","Le polo","Le hurling"},
    {5,2,"Quel pays a gagné le plus de Coupes du monde de rugby à XIII ?","L'Australie","L'Angleterre","La Nouvelle-Zélande","La France"},
    {5,2,"Combien de points vaut un panier à 1 point en basket ?","1","2","3","0,5"},
    {5,2,"Quel athlète a sauté le plus loin en longueur ?","Mike Powell","Bob Beamon","Carl Lewis","Jesse Owens"},
    {5,2,"Quel sport se pratique avec un ballon et un filet bas ?","Le tennis","Le volley-ball","Le badminton","Le ping-pong"},
    {5,2,"Quel pays a inventé le netball ?","L'Angleterre","Les États-Unis","L'Australie","La Nouvelle-Zélande"},
};

// ═══════════════════════════════════════════════════════════════════════════════
// TABLEAU GLOBAL — accès unifié par catégorie
// ═══════════════════════════════════════════════════════════════════════════════
static const TriviaQuestion* const TRIVIA_BANKS[TRIVIA_NCAT] = {
    QUESTIONS_GEO, QUESTIONS_ENT, QUESTIONS_HIST,
    QUESTIONS_ART, QUESTIONS_SCI, QUESTIONS_SPO
};
static const uint8_t TRIVIA_BANK_SIZES[TRIVIA_NCAT] = {
    TRIVIA_Q_GEO, TRIVIA_Q_ENT, TRIVIA_Q_HIST,
    TRIVIA_Q_ART, TRIVIA_Q_SCI, TRIVIA_Q_SPO
};
